// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.addons

import io.stigg.core.JsonValue
import io.stigg.core.http.Headers
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AddonUpdateParamsTest {

    @Test
    fun create() {
        AddonUpdateParams.builder()
            .id("x")
            .xAccountId("X-ACCOUNT-ID")
            .xEnvironmentId("X-ENVIRONMENT-ID")
            .billingId("billingId")
            .charges(
                AddonUpdateParams.Charges.builder()
                    .pricingType(AddonUpdateParams.Charges.PricingType.FREE)
                    .billingId("billingId")
                    .addMinimumSpend(
                        AddonUpdateParams.Charges.MinimumSpend.builder()
                            .billingPeriod(
                                AddonUpdateParams.Charges.MinimumSpend.BillingPeriod.MONTHLY
                            )
                            .minimum(
                                AddonUpdateParams.Charges.MinimumSpend.Minimum.builder()
                                    .amount(0.0)
                                    .currency(
                                        AddonUpdateParams.Charges.MinimumSpend.Minimum.Currency.USD
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .overageBillingPeriod(
                        AddonUpdateParams.Charges.OverageBillingPeriod.ON_SUBSCRIPTION_RENEWAL
                    )
                    .addOveragePricingModel(
                        AddonUpdateParams.Charges.OveragePricingModel.builder()
                            .addPricePeriod(
                                AddonUpdateParams.Charges.OveragePricingModel.PricePeriod.builder()
                                    .billingPeriod(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .BillingPeriod
                                            .MONTHLY
                                    )
                                    .billingCountryCode("billingCountryCode")
                                    .blockSize(0.0)
                                    .creditGrantCadence(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .CreditGrantCadence
                                            .BEGINNING_OF_BILLING_PERIOD
                                    )
                                    .creditRate(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .CreditRate
                                            .builder()
                                            .amount(1.0)
                                            .currencyId("currencyId")
                                            .costFormula("costFormula")
                                            .build()
                                    )
                                    .price(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .Price
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .PricePeriod
                                                    .Price
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .addTier(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .Tier
                                            .builder()
                                            .flatPrice(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .PricePeriod
                                                    .Tier
                                                    .FlatPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        AddonUpdateParams.Charges
                                                            .OveragePricingModel
                                                            .PricePeriod
                                                            .Tier
                                                            .FlatPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .unitPrice(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .PricePeriod
                                                    .Tier
                                                    .UnitPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        AddonUpdateParams.Charges
                                                            .OveragePricingModel
                                                            .PricePeriod
                                                            .Tier
                                                            .UnitPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .upTo(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .creditEntitlement(
                                AddonUpdateParams.Charges.OveragePricingModel.CreditEntitlement
                                    .builder()
                                    .amount(1.0)
                                    .cadence(
                                        AddonUpdateParams.Charges.OveragePricingModel
                                            .CreditEntitlement
                                            .Cadence
                                            .MONTH
                                    )
                                    .customCurrencyId("customCurrencyId")
                                    .build()
                            )
                            .currencyId("currencyId")
                            .entitlement(
                                AddonUpdateParams.Charges.OveragePricingModel.Entitlement.builder()
                                    .featureId("featureId")
                                    .hasSoftLimit(true)
                                    .hasUnlimitedUsage(true)
                                    .monthlyResetPeriodConfiguration(
                                        AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                            .MonthlyResetPeriodConfiguration
                                            .builder()
                                            .accordingTo(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .Entitlement
                                                    .MonthlyResetPeriodConfiguration
                                                    .AccordingTo
                                                    .SUBSCRIPTION_START
                                            )
                                            .build()
                                    )
                                    .resetPeriod(
                                        AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                            .ResetPeriod
                                            .YEAR
                                    )
                                    .usageLimit(0.0)
                                    .weeklyResetPeriodConfiguration(
                                        AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                            .WeeklyResetPeriodConfiguration
                                            .builder()
                                            .accordingTo(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .Entitlement
                                                    .WeeklyResetPeriodConfiguration
                                                    .AccordingTo
                                                    .SUBSCRIPTION_START
                                            )
                                            .build()
                                    )
                                    .yearlyResetPeriodConfiguration(
                                        AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                            .YearlyResetPeriodConfiguration
                                            .builder()
                                            .accordingTo(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .Entitlement
                                                    .YearlyResetPeriodConfiguration
                                                    .AccordingTo
                                                    .SUBSCRIPTION_START
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .featureId("featureId")
                            .build()
                    )
                    .addPricingModel(
                        AddonUpdateParams.Charges.PricingModel.builder()
                            .billingModel(
                                AddonUpdateParams.Charges.PricingModel.BillingModel.FLAT_FEE
                            )
                            .addPricePeriod(
                                AddonUpdateParams.Charges.PricingModel.PricePeriod.builder()
                                    .billingPeriod(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod
                                            .BillingPeriod
                                            .MONTHLY
                                    )
                                    .billingCountryCode("billingCountryCode")
                                    .blockSize(0.0)
                                    .creditGrantCadence(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod
                                            .CreditGrantCadence
                                            .BEGINNING_OF_BILLING_PERIOD
                                    )
                                    .creditRate(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod
                                            .CreditRate
                                            .builder()
                                            .amount(1.0)
                                            .currencyId("currencyId")
                                            .costFormula("costFormula")
                                            .build()
                                    )
                                    .price(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod.Price
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                    .Price
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .addTier(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod.Tier
                                            .builder()
                                            .flatPrice(
                                                AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                    .Tier
                                                    .FlatPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        AddonUpdateParams.Charges.PricingModel
                                                            .PricePeriod
                                                            .Tier
                                                            .FlatPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .unitPrice(
                                                AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                    .Tier
                                                    .UnitPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        AddonUpdateParams.Charges.PricingModel
                                                            .PricePeriod
                                                            .Tier
                                                            .UnitPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .upTo(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .billingCadence(
                                AddonUpdateParams.Charges.PricingModel.BillingCadence.RECURRING
                            )
                            .featureId("featureId")
                            .maxUnitQuantity(1L)
                            .minUnitQuantity(1L)
                            .monthlyResetPeriodConfiguration(
                                AddonUpdateParams.Charges.PricingModel
                                    .MonthlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        AddonUpdateParams.Charges.PricingModel
                                            .MonthlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .resetPeriod(AddonUpdateParams.Charges.PricingModel.ResetPeriod.YEAR)
                            .tiersMode(AddonUpdateParams.Charges.PricingModel.TiersMode.VOLUME)
                            .topUpCustomCurrencyId("topUpCustomCurrencyId")
                            .weeklyResetPeriodConfiguration(
                                AddonUpdateParams.Charges.PricingModel
                                    .WeeklyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        AddonUpdateParams.Charges.PricingModel
                                            .WeeklyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .yearlyResetPeriodConfiguration(
                                AddonUpdateParams.Charges.PricingModel
                                    .YearlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        AddonUpdateParams.Charges.PricingModel
                                            .YearlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .addDependency("string")
            .description("description")
            .displayName("displayName")
            .maxQuantity(1L)
            .metadata(
                AddonUpdateParams.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
            .status(AddonUpdateParams.Status.DRAFT)
            .build()
    }

    @Test
    fun pathParams() {
        val params = AddonUpdateParams.builder().id("x").build()

        assertThat(params._pathParam(0)).isEqualTo("x")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun headers() {
        val params =
            AddonUpdateParams.builder()
                .id("x")
                .xAccountId("X-ACCOUNT-ID")
                .xEnvironmentId("X-ENVIRONMENT-ID")
                .billingId("billingId")
                .charges(
                    AddonUpdateParams.Charges.builder()
                        .pricingType(AddonUpdateParams.Charges.PricingType.FREE)
                        .billingId("billingId")
                        .addMinimumSpend(
                            AddonUpdateParams.Charges.MinimumSpend.builder()
                                .billingPeriod(
                                    AddonUpdateParams.Charges.MinimumSpend.BillingPeriod.MONTHLY
                                )
                                .minimum(
                                    AddonUpdateParams.Charges.MinimumSpend.Minimum.builder()
                                        .amount(0.0)
                                        .currency(
                                            AddonUpdateParams.Charges.MinimumSpend.Minimum.Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .overageBillingPeriod(
                            AddonUpdateParams.Charges.OverageBillingPeriod.ON_SUBSCRIPTION_RENEWAL
                        )
                        .addOveragePricingModel(
                            AddonUpdateParams.Charges.OveragePricingModel.builder()
                                .addPricePeriod(
                                    AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                        .builder()
                                        .billingPeriod(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .BillingPeriod
                                                .MONTHLY
                                        )
                                        .billingCountryCode("billingCountryCode")
                                        .blockSize(0.0)
                                        .creditGrantCadence(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .CreditGrantCadence
                                                .BEGINNING_OF_BILLING_PERIOD
                                        )
                                        .creditRate(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .CreditRate
                                                .builder()
                                                .amount(1.0)
                                                .currencyId("currencyId")
                                                .costFormula("costFormula")
                                                .build()
                                        )
                                        .price(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .Price
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .PricePeriod
                                                        .Price
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .addTier(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .Tier
                                                .builder()
                                                .flatPrice(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .FlatPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            AddonUpdateParams.Charges
                                                                .OveragePricingModel
                                                                .PricePeriod
                                                                .Tier
                                                                .FlatPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .unitPrice(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .UnitPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            AddonUpdateParams.Charges
                                                                .OveragePricingModel
                                                                .PricePeriod
                                                                .Tier
                                                                .UnitPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .upTo(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .creditEntitlement(
                                    AddonUpdateParams.Charges.OveragePricingModel.CreditEntitlement
                                        .builder()
                                        .amount(1.0)
                                        .cadence(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .CreditEntitlement
                                                .Cadence
                                                .MONTH
                                        )
                                        .customCurrencyId("customCurrencyId")
                                        .build()
                                )
                                .currencyId("currencyId")
                                .entitlement(
                                    AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                        .builder()
                                        .featureId("featureId")
                                        .hasSoftLimit(true)
                                        .hasUnlimitedUsage(true)
                                        .monthlyResetPeriodConfiguration(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .Entitlement
                                                .MonthlyResetPeriodConfiguration
                                                .builder()
                                                .accordingTo(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .Entitlement
                                                        .MonthlyResetPeriodConfiguration
                                                        .AccordingTo
                                                        .SUBSCRIPTION_START
                                                )
                                                .build()
                                        )
                                        .resetPeriod(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .Entitlement
                                                .ResetPeriod
                                                .YEAR
                                        )
                                        .usageLimit(0.0)
                                        .weeklyResetPeriodConfiguration(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .Entitlement
                                                .WeeklyResetPeriodConfiguration
                                                .builder()
                                                .accordingTo(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .Entitlement
                                                        .WeeklyResetPeriodConfiguration
                                                        .AccordingTo
                                                        .SUBSCRIPTION_START
                                                )
                                                .build()
                                        )
                                        .yearlyResetPeriodConfiguration(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .Entitlement
                                                .YearlyResetPeriodConfiguration
                                                .builder()
                                                .accordingTo(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .Entitlement
                                                        .YearlyResetPeriodConfiguration
                                                        .AccordingTo
                                                        .SUBSCRIPTION_START
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .featureId("featureId")
                                .build()
                        )
                        .addPricingModel(
                            AddonUpdateParams.Charges.PricingModel.builder()
                                .billingModel(
                                    AddonUpdateParams.Charges.PricingModel.BillingModel.FLAT_FEE
                                )
                                .addPricePeriod(
                                    AddonUpdateParams.Charges.PricingModel.PricePeriod.builder()
                                        .billingPeriod(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                .BillingPeriod
                                                .MONTHLY
                                        )
                                        .billingCountryCode("billingCountryCode")
                                        .blockSize(0.0)
                                        .creditGrantCadence(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                .CreditGrantCadence
                                                .BEGINNING_OF_BILLING_PERIOD
                                        )
                                        .creditRate(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                .CreditRate
                                                .builder()
                                                .amount(1.0)
                                                .currencyId("currencyId")
                                                .costFormula("costFormula")
                                                .build()
                                        )
                                        .price(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod.Price
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    AddonUpdateParams.Charges.PricingModel
                                                        .PricePeriod
                                                        .Price
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .addTier(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod.Tier
                                                .builder()
                                                .flatPrice(
                                                    AddonUpdateParams.Charges.PricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .FlatPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            AddonUpdateParams.Charges.PricingModel
                                                                .PricePeriod
                                                                .Tier
                                                                .FlatPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .unitPrice(
                                                    AddonUpdateParams.Charges.PricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .UnitPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            AddonUpdateParams.Charges.PricingModel
                                                                .PricePeriod
                                                                .Tier
                                                                .UnitPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .upTo(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .billingCadence(
                                    AddonUpdateParams.Charges.PricingModel.BillingCadence.RECURRING
                                )
                                .featureId("featureId")
                                .maxUnitQuantity(1L)
                                .minUnitQuantity(1L)
                                .monthlyResetPeriodConfiguration(
                                    AddonUpdateParams.Charges.PricingModel
                                        .MonthlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            AddonUpdateParams.Charges.PricingModel
                                                .MonthlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .resetPeriod(
                                    AddonUpdateParams.Charges.PricingModel.ResetPeriod.YEAR
                                )
                                .tiersMode(AddonUpdateParams.Charges.PricingModel.TiersMode.VOLUME)
                                .topUpCustomCurrencyId("topUpCustomCurrencyId")
                                .weeklyResetPeriodConfiguration(
                                    AddonUpdateParams.Charges.PricingModel
                                        .WeeklyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            AddonUpdateParams.Charges.PricingModel
                                                .WeeklyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .yearlyResetPeriodConfiguration(
                                    AddonUpdateParams.Charges.PricingModel
                                        .YearlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            AddonUpdateParams.Charges.PricingModel
                                                .YearlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .addDependency("string")
                .description("description")
                .displayName("displayName")
                .maxQuantity(1L)
                .metadata(
                    AddonUpdateParams.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .status(AddonUpdateParams.Status.DRAFT)
                .build()

        val headers = params._headers()

        assertThat(headers)
            .isEqualTo(
                Headers.builder()
                    .put("X-ACCOUNT-ID", "X-ACCOUNT-ID")
                    .put("X-ENVIRONMENT-ID", "X-ENVIRONMENT-ID")
                    .build()
            )
    }

    @Test
    fun headersWithoutOptionalFields() {
        val params = AddonUpdateParams.builder().id("x").build()

        val headers = params._headers()

        assertThat(headers).isEqualTo(Headers.builder().build())
    }

    @Test
    fun body() {
        val params =
            AddonUpdateParams.builder()
                .id("x")
                .xAccountId("X-ACCOUNT-ID")
                .xEnvironmentId("X-ENVIRONMENT-ID")
                .billingId("billingId")
                .charges(
                    AddonUpdateParams.Charges.builder()
                        .pricingType(AddonUpdateParams.Charges.PricingType.FREE)
                        .billingId("billingId")
                        .addMinimumSpend(
                            AddonUpdateParams.Charges.MinimumSpend.builder()
                                .billingPeriod(
                                    AddonUpdateParams.Charges.MinimumSpend.BillingPeriod.MONTHLY
                                )
                                .minimum(
                                    AddonUpdateParams.Charges.MinimumSpend.Minimum.builder()
                                        .amount(0.0)
                                        .currency(
                                            AddonUpdateParams.Charges.MinimumSpend.Minimum.Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .overageBillingPeriod(
                            AddonUpdateParams.Charges.OverageBillingPeriod.ON_SUBSCRIPTION_RENEWAL
                        )
                        .addOveragePricingModel(
                            AddonUpdateParams.Charges.OveragePricingModel.builder()
                                .addPricePeriod(
                                    AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                        .builder()
                                        .billingPeriod(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .BillingPeriod
                                                .MONTHLY
                                        )
                                        .billingCountryCode("billingCountryCode")
                                        .blockSize(0.0)
                                        .creditGrantCadence(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .CreditGrantCadence
                                                .BEGINNING_OF_BILLING_PERIOD
                                        )
                                        .creditRate(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .CreditRate
                                                .builder()
                                                .amount(1.0)
                                                .currencyId("currencyId")
                                                .costFormula("costFormula")
                                                .build()
                                        )
                                        .price(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .Price
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .PricePeriod
                                                        .Price
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .addTier(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .PricePeriod
                                                .Tier
                                                .builder()
                                                .flatPrice(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .FlatPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            AddonUpdateParams.Charges
                                                                .OveragePricingModel
                                                                .PricePeriod
                                                                .Tier
                                                                .FlatPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .unitPrice(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .UnitPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            AddonUpdateParams.Charges
                                                                .OveragePricingModel
                                                                .PricePeriod
                                                                .Tier
                                                                .UnitPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .upTo(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .creditEntitlement(
                                    AddonUpdateParams.Charges.OveragePricingModel.CreditEntitlement
                                        .builder()
                                        .amount(1.0)
                                        .cadence(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .CreditEntitlement
                                                .Cadence
                                                .MONTH
                                        )
                                        .customCurrencyId("customCurrencyId")
                                        .build()
                                )
                                .currencyId("currencyId")
                                .entitlement(
                                    AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                        .builder()
                                        .featureId("featureId")
                                        .hasSoftLimit(true)
                                        .hasUnlimitedUsage(true)
                                        .monthlyResetPeriodConfiguration(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .Entitlement
                                                .MonthlyResetPeriodConfiguration
                                                .builder()
                                                .accordingTo(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .Entitlement
                                                        .MonthlyResetPeriodConfiguration
                                                        .AccordingTo
                                                        .SUBSCRIPTION_START
                                                )
                                                .build()
                                        )
                                        .resetPeriod(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .Entitlement
                                                .ResetPeriod
                                                .YEAR
                                        )
                                        .usageLimit(0.0)
                                        .weeklyResetPeriodConfiguration(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .Entitlement
                                                .WeeklyResetPeriodConfiguration
                                                .builder()
                                                .accordingTo(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .Entitlement
                                                        .WeeklyResetPeriodConfiguration
                                                        .AccordingTo
                                                        .SUBSCRIPTION_START
                                                )
                                                .build()
                                        )
                                        .yearlyResetPeriodConfiguration(
                                            AddonUpdateParams.Charges.OveragePricingModel
                                                .Entitlement
                                                .YearlyResetPeriodConfiguration
                                                .builder()
                                                .accordingTo(
                                                    AddonUpdateParams.Charges.OveragePricingModel
                                                        .Entitlement
                                                        .YearlyResetPeriodConfiguration
                                                        .AccordingTo
                                                        .SUBSCRIPTION_START
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .featureId("featureId")
                                .build()
                        )
                        .addPricingModel(
                            AddonUpdateParams.Charges.PricingModel.builder()
                                .billingModel(
                                    AddonUpdateParams.Charges.PricingModel.BillingModel.FLAT_FEE
                                )
                                .addPricePeriod(
                                    AddonUpdateParams.Charges.PricingModel.PricePeriod.builder()
                                        .billingPeriod(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                .BillingPeriod
                                                .MONTHLY
                                        )
                                        .billingCountryCode("billingCountryCode")
                                        .blockSize(0.0)
                                        .creditGrantCadence(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                .CreditGrantCadence
                                                .BEGINNING_OF_BILLING_PERIOD
                                        )
                                        .creditRate(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                .CreditRate
                                                .builder()
                                                .amount(1.0)
                                                .currencyId("currencyId")
                                                .costFormula("costFormula")
                                                .build()
                                        )
                                        .price(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod.Price
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    AddonUpdateParams.Charges.PricingModel
                                                        .PricePeriod
                                                        .Price
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .addTier(
                                            AddonUpdateParams.Charges.PricingModel.PricePeriod.Tier
                                                .builder()
                                                .flatPrice(
                                                    AddonUpdateParams.Charges.PricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .FlatPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            AddonUpdateParams.Charges.PricingModel
                                                                .PricePeriod
                                                                .Tier
                                                                .FlatPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .unitPrice(
                                                    AddonUpdateParams.Charges.PricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .UnitPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            AddonUpdateParams.Charges.PricingModel
                                                                .PricePeriod
                                                                .Tier
                                                                .UnitPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .upTo(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .billingCadence(
                                    AddonUpdateParams.Charges.PricingModel.BillingCadence.RECURRING
                                )
                                .featureId("featureId")
                                .maxUnitQuantity(1L)
                                .minUnitQuantity(1L)
                                .monthlyResetPeriodConfiguration(
                                    AddonUpdateParams.Charges.PricingModel
                                        .MonthlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            AddonUpdateParams.Charges.PricingModel
                                                .MonthlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .resetPeriod(
                                    AddonUpdateParams.Charges.PricingModel.ResetPeriod.YEAR
                                )
                                .tiersMode(AddonUpdateParams.Charges.PricingModel.TiersMode.VOLUME)
                                .topUpCustomCurrencyId("topUpCustomCurrencyId")
                                .weeklyResetPeriodConfiguration(
                                    AddonUpdateParams.Charges.PricingModel
                                        .WeeklyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            AddonUpdateParams.Charges.PricingModel
                                                .WeeklyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .yearlyResetPeriodConfiguration(
                                    AddonUpdateParams.Charges.PricingModel
                                        .YearlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            AddonUpdateParams.Charges.PricingModel
                                                .YearlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .addDependency("string")
                .description("description")
                .displayName("displayName")
                .maxQuantity(1L)
                .metadata(
                    AddonUpdateParams.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .status(AddonUpdateParams.Status.DRAFT)
                .build()

        val body = params._body()

        assertThat(body.billingId()).contains("billingId")
        assertThat(body.charges())
            .contains(
                AddonUpdateParams.Charges.builder()
                    .pricingType(AddonUpdateParams.Charges.PricingType.FREE)
                    .billingId("billingId")
                    .addMinimumSpend(
                        AddonUpdateParams.Charges.MinimumSpend.builder()
                            .billingPeriod(
                                AddonUpdateParams.Charges.MinimumSpend.BillingPeriod.MONTHLY
                            )
                            .minimum(
                                AddonUpdateParams.Charges.MinimumSpend.Minimum.builder()
                                    .amount(0.0)
                                    .currency(
                                        AddonUpdateParams.Charges.MinimumSpend.Minimum.Currency.USD
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .overageBillingPeriod(
                        AddonUpdateParams.Charges.OverageBillingPeriod.ON_SUBSCRIPTION_RENEWAL
                    )
                    .addOveragePricingModel(
                        AddonUpdateParams.Charges.OveragePricingModel.builder()
                            .addPricePeriod(
                                AddonUpdateParams.Charges.OveragePricingModel.PricePeriod.builder()
                                    .billingPeriod(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .BillingPeriod
                                            .MONTHLY
                                    )
                                    .billingCountryCode("billingCountryCode")
                                    .blockSize(0.0)
                                    .creditGrantCadence(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .CreditGrantCadence
                                            .BEGINNING_OF_BILLING_PERIOD
                                    )
                                    .creditRate(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .CreditRate
                                            .builder()
                                            .amount(1.0)
                                            .currencyId("currencyId")
                                            .costFormula("costFormula")
                                            .build()
                                    )
                                    .price(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .Price
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .PricePeriod
                                                    .Price
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .addTier(
                                        AddonUpdateParams.Charges.OveragePricingModel.PricePeriod
                                            .Tier
                                            .builder()
                                            .flatPrice(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .PricePeriod
                                                    .Tier
                                                    .FlatPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        AddonUpdateParams.Charges
                                                            .OveragePricingModel
                                                            .PricePeriod
                                                            .Tier
                                                            .FlatPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .unitPrice(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .PricePeriod
                                                    .Tier
                                                    .UnitPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        AddonUpdateParams.Charges
                                                            .OveragePricingModel
                                                            .PricePeriod
                                                            .Tier
                                                            .UnitPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .upTo(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .creditEntitlement(
                                AddonUpdateParams.Charges.OveragePricingModel.CreditEntitlement
                                    .builder()
                                    .amount(1.0)
                                    .cadence(
                                        AddonUpdateParams.Charges.OveragePricingModel
                                            .CreditEntitlement
                                            .Cadence
                                            .MONTH
                                    )
                                    .customCurrencyId("customCurrencyId")
                                    .build()
                            )
                            .currencyId("currencyId")
                            .entitlement(
                                AddonUpdateParams.Charges.OveragePricingModel.Entitlement.builder()
                                    .featureId("featureId")
                                    .hasSoftLimit(true)
                                    .hasUnlimitedUsage(true)
                                    .monthlyResetPeriodConfiguration(
                                        AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                            .MonthlyResetPeriodConfiguration
                                            .builder()
                                            .accordingTo(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .Entitlement
                                                    .MonthlyResetPeriodConfiguration
                                                    .AccordingTo
                                                    .SUBSCRIPTION_START
                                            )
                                            .build()
                                    )
                                    .resetPeriod(
                                        AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                            .ResetPeriod
                                            .YEAR
                                    )
                                    .usageLimit(0.0)
                                    .weeklyResetPeriodConfiguration(
                                        AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                            .WeeklyResetPeriodConfiguration
                                            .builder()
                                            .accordingTo(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .Entitlement
                                                    .WeeklyResetPeriodConfiguration
                                                    .AccordingTo
                                                    .SUBSCRIPTION_START
                                            )
                                            .build()
                                    )
                                    .yearlyResetPeriodConfiguration(
                                        AddonUpdateParams.Charges.OveragePricingModel.Entitlement
                                            .YearlyResetPeriodConfiguration
                                            .builder()
                                            .accordingTo(
                                                AddonUpdateParams.Charges.OveragePricingModel
                                                    .Entitlement
                                                    .YearlyResetPeriodConfiguration
                                                    .AccordingTo
                                                    .SUBSCRIPTION_START
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .featureId("featureId")
                            .build()
                    )
                    .addPricingModel(
                        AddonUpdateParams.Charges.PricingModel.builder()
                            .billingModel(
                                AddonUpdateParams.Charges.PricingModel.BillingModel.FLAT_FEE
                            )
                            .addPricePeriod(
                                AddonUpdateParams.Charges.PricingModel.PricePeriod.builder()
                                    .billingPeriod(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod
                                            .BillingPeriod
                                            .MONTHLY
                                    )
                                    .billingCountryCode("billingCountryCode")
                                    .blockSize(0.0)
                                    .creditGrantCadence(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod
                                            .CreditGrantCadence
                                            .BEGINNING_OF_BILLING_PERIOD
                                    )
                                    .creditRate(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod
                                            .CreditRate
                                            .builder()
                                            .amount(1.0)
                                            .currencyId("currencyId")
                                            .costFormula("costFormula")
                                            .build()
                                    )
                                    .price(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod.Price
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                    .Price
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .addTier(
                                        AddonUpdateParams.Charges.PricingModel.PricePeriod.Tier
                                            .builder()
                                            .flatPrice(
                                                AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                    .Tier
                                                    .FlatPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        AddonUpdateParams.Charges.PricingModel
                                                            .PricePeriod
                                                            .Tier
                                                            .FlatPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .unitPrice(
                                                AddonUpdateParams.Charges.PricingModel.PricePeriod
                                                    .Tier
                                                    .UnitPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        AddonUpdateParams.Charges.PricingModel
                                                            .PricePeriod
                                                            .Tier
                                                            .UnitPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .upTo(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .billingCadence(
                                AddonUpdateParams.Charges.PricingModel.BillingCadence.RECURRING
                            )
                            .featureId("featureId")
                            .maxUnitQuantity(1L)
                            .minUnitQuantity(1L)
                            .monthlyResetPeriodConfiguration(
                                AddonUpdateParams.Charges.PricingModel
                                    .MonthlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        AddonUpdateParams.Charges.PricingModel
                                            .MonthlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .resetPeriod(AddonUpdateParams.Charges.PricingModel.ResetPeriod.YEAR)
                            .tiersMode(AddonUpdateParams.Charges.PricingModel.TiersMode.VOLUME)
                            .topUpCustomCurrencyId("topUpCustomCurrencyId")
                            .weeklyResetPeriodConfiguration(
                                AddonUpdateParams.Charges.PricingModel
                                    .WeeklyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        AddonUpdateParams.Charges.PricingModel
                                            .WeeklyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .yearlyResetPeriodConfiguration(
                                AddonUpdateParams.Charges.PricingModel
                                    .YearlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        AddonUpdateParams.Charges.PricingModel
                                            .YearlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.dependencies().getOrNull()).containsExactly("string")
        assertThat(body.description()).contains("description")
        assertThat(body.displayName()).contains("displayName")
        assertThat(body.maxQuantity()).contains(1L)
        assertThat(body.metadata())
            .contains(
                AddonUpdateParams.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(body.status()).contains(AddonUpdateParams.Status.DRAFT)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = AddonUpdateParams.builder().id("x").build()

        val body = params._body()
    }
}
