// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.addons

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.stigg.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SetPackagePricingTest {

    @Test
    fun create() {
        val setPackagePricing =
            SetPackagePricing.builder()
                .pricingType(SetPackagePricing.PricingType.FREE)
                .billingId("billingId")
                .addMinimumSpend(
                    SetPackagePricing.MinimumSpend.builder()
                        .billingPeriod(SetPackagePricing.MinimumSpend.BillingPeriod.MONTHLY)
                        .minimum(
                            SetPackagePricing.MinimumSpend.Minimum.builder()
                                .amount(0.0)
                                .currency(SetPackagePricing.MinimumSpend.Minimum.Currency.USD)
                                .build()
                        )
                        .build()
                )
                .overageBillingPeriod(
                    SetPackagePricing.OverageBillingPeriod.ON_SUBSCRIPTION_RENEWAL
                )
                .addOveragePricingModel(
                    SetPackagePricing.OveragePricingModel.builder()
                        .billingModel(SetPackagePricing.OveragePricingModel.BillingModel.FLAT_FEE)
                        .addPricePeriod(
                            SetPackagePricing.OveragePricingModel.PricePeriod.builder()
                                .billingPeriod(
                                    SetPackagePricing.OveragePricingModel.PricePeriod.BillingPeriod
                                        .MONTHLY
                                )
                                .billingCountryCode("billingCountryCode")
                                .blockSize(0.0)
                                .creditGrantCadence(
                                    SetPackagePricing.OveragePricingModel.PricePeriod
                                        .CreditGrantCadence
                                        .BEGINNING_OF_BILLING_PERIOD
                                )
                                .creditRate(
                                    SetPackagePricing.OveragePricingModel.PricePeriod.CreditRate
                                        .builder()
                                        .amount(1.0)
                                        .currencyId("currencyId")
                                        .costFormula("costFormula")
                                        .build()
                                )
                                .price(
                                    SetPackagePricing.OveragePricingModel.PricePeriod.Price
                                        .builder()
                                        .amount(0.0)
                                        .currency(
                                            SetPackagePricing.OveragePricingModel.PricePeriod.Price
                                                .Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .addTier(
                                    SetPackagePricing.OveragePricingModel.PricePeriod.Tier.builder()
                                        .flatPrice(
                                            SetPackagePricing.OveragePricingModel.PricePeriod.Tier
                                                .FlatPrice
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SetPackagePricing.OveragePricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .FlatPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .unitPrice(
                                            SetPackagePricing.OveragePricingModel.PricePeriod.Tier
                                                .UnitPrice
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SetPackagePricing.OveragePricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .UnitPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .upTo(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .billingCadence(
                            SetPackagePricing.OveragePricingModel.BillingCadence.RECURRING
                        )
                        .entitlement(
                            SetPackagePricing.OveragePricingModel.Entitlement.builder()
                                .featureId("featureId")
                                .hasSoftLimit(true)
                                .hasUnlimitedUsage(true)
                                .monthlyResetPeriodConfiguration(
                                    SetPackagePricing.OveragePricingModel.Entitlement
                                        .MonthlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            SetPackagePricing.OveragePricingModel.Entitlement
                                                .MonthlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .resetPeriod(
                                    SetPackagePricing.OveragePricingModel.Entitlement.ResetPeriod
                                        .YEAR
                                )
                                .usageLimit(0.0)
                                .weeklyResetPeriodConfiguration(
                                    SetPackagePricing.OveragePricingModel.Entitlement
                                        .WeeklyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            SetPackagePricing.OveragePricingModel.Entitlement
                                                .WeeklyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .yearlyResetPeriodConfiguration(
                                    SetPackagePricing.OveragePricingModel.Entitlement
                                        .YearlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            SetPackagePricing.OveragePricingModel.Entitlement
                                                .YearlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .featureId("featureId")
                        .topUpCustomCurrencyId("topUpCustomCurrencyId")
                        .build()
                )
                .addPricingModel(
                    SetPackagePricing.PricingModel.builder()
                        .billingModel(SetPackagePricing.PricingModel.BillingModel.FLAT_FEE)
                        .addPricePeriod(
                            SetPackagePricing.PricingModel.PricePeriod.builder()
                                .billingPeriod(
                                    SetPackagePricing.PricingModel.PricePeriod.BillingPeriod.MONTHLY
                                )
                                .billingCountryCode("billingCountryCode")
                                .blockSize(0.0)
                                .creditGrantCadence(
                                    SetPackagePricing.PricingModel.PricePeriod.CreditGrantCadence
                                        .BEGINNING_OF_BILLING_PERIOD
                                )
                                .creditRate(
                                    SetPackagePricing.PricingModel.PricePeriod.CreditRate.builder()
                                        .amount(1.0)
                                        .currencyId("currencyId")
                                        .costFormula("costFormula")
                                        .build()
                                )
                                .price(
                                    SetPackagePricing.PricingModel.PricePeriod.Price.builder()
                                        .amount(0.0)
                                        .currency(
                                            SetPackagePricing.PricingModel.PricePeriod.Price
                                                .Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .addTier(
                                    SetPackagePricing.PricingModel.PricePeriod.Tier.builder()
                                        .flatPrice(
                                            SetPackagePricing.PricingModel.PricePeriod.Tier
                                                .FlatPrice
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SetPackagePricing.PricingModel.PricePeriod.Tier
                                                        .FlatPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .unitPrice(
                                            SetPackagePricing.PricingModel.PricePeriod.Tier
                                                .UnitPrice
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SetPackagePricing.PricingModel.PricePeriod.Tier
                                                        .UnitPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .upTo(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .billingCadence(SetPackagePricing.PricingModel.BillingCadence.RECURRING)
                        .featureId("featureId")
                        .maxUnitQuantity(1L)
                        .minUnitQuantity(1L)
                        .monthlyResetPeriodConfiguration(
                            SetPackagePricing.PricingModel.MonthlyResetPeriodConfiguration.builder()
                                .accordingTo(
                                    SetPackagePricing.PricingModel.MonthlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .resetPeriod(SetPackagePricing.PricingModel.ResetPeriod.YEAR)
                        .tiersMode(SetPackagePricing.PricingModel.TiersMode.VOLUME)
                        .topUpCustomCurrencyId("topUpCustomCurrencyId")
                        .weeklyResetPeriodConfiguration(
                            SetPackagePricing.PricingModel.WeeklyResetPeriodConfiguration.builder()
                                .accordingTo(
                                    SetPackagePricing.PricingModel.WeeklyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .yearlyResetPeriodConfiguration(
                            SetPackagePricing.PricingModel.YearlyResetPeriodConfiguration.builder()
                                .accordingTo(
                                    SetPackagePricing.PricingModel.YearlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(setPackagePricing.pricingType()).isEqualTo(SetPackagePricing.PricingType.FREE)
        assertThat(setPackagePricing.billingId()).contains("billingId")
        assertThat(setPackagePricing.minimumSpend().getOrNull())
            .containsExactly(
                SetPackagePricing.MinimumSpend.builder()
                    .billingPeriod(SetPackagePricing.MinimumSpend.BillingPeriod.MONTHLY)
                    .minimum(
                        SetPackagePricing.MinimumSpend.Minimum.builder()
                            .amount(0.0)
                            .currency(SetPackagePricing.MinimumSpend.Minimum.Currency.USD)
                            .build()
                    )
                    .build()
            )
        assertThat(setPackagePricing.overageBillingPeriod())
            .contains(SetPackagePricing.OverageBillingPeriod.ON_SUBSCRIPTION_RENEWAL)
        assertThat(setPackagePricing.overagePricingModels().getOrNull())
            .containsExactly(
                SetPackagePricing.OveragePricingModel.builder()
                    .billingModel(SetPackagePricing.OveragePricingModel.BillingModel.FLAT_FEE)
                    .addPricePeriod(
                        SetPackagePricing.OveragePricingModel.PricePeriod.builder()
                            .billingPeriod(
                                SetPackagePricing.OveragePricingModel.PricePeriod.BillingPeriod
                                    .MONTHLY
                            )
                            .billingCountryCode("billingCountryCode")
                            .blockSize(0.0)
                            .creditGrantCadence(
                                SetPackagePricing.OveragePricingModel.PricePeriod.CreditGrantCadence
                                    .BEGINNING_OF_BILLING_PERIOD
                            )
                            .creditRate(
                                SetPackagePricing.OveragePricingModel.PricePeriod.CreditRate
                                    .builder()
                                    .amount(1.0)
                                    .currencyId("currencyId")
                                    .costFormula("costFormula")
                                    .build()
                            )
                            .price(
                                SetPackagePricing.OveragePricingModel.PricePeriod.Price.builder()
                                    .amount(0.0)
                                    .currency(
                                        SetPackagePricing.OveragePricingModel.PricePeriod.Price
                                            .Currency
                                            .USD
                                    )
                                    .build()
                            )
                            .addTier(
                                SetPackagePricing.OveragePricingModel.PricePeriod.Tier.builder()
                                    .flatPrice(
                                        SetPackagePricing.OveragePricingModel.PricePeriod.Tier
                                            .FlatPrice
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                SetPackagePricing.OveragePricingModel.PricePeriod
                                                    .Tier
                                                    .FlatPrice
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .unitPrice(
                                        SetPackagePricing.OveragePricingModel.PricePeriod.Tier
                                            .UnitPrice
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                SetPackagePricing.OveragePricingModel.PricePeriod
                                                    .Tier
                                                    .UnitPrice
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .upTo(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .billingCadence(SetPackagePricing.OveragePricingModel.BillingCadence.RECURRING)
                    .entitlement(
                        SetPackagePricing.OveragePricingModel.Entitlement.builder()
                            .featureId("featureId")
                            .hasSoftLimit(true)
                            .hasUnlimitedUsage(true)
                            .monthlyResetPeriodConfiguration(
                                SetPackagePricing.OveragePricingModel.Entitlement
                                    .MonthlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        SetPackagePricing.OveragePricingModel.Entitlement
                                            .MonthlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .resetPeriod(
                                SetPackagePricing.OveragePricingModel.Entitlement.ResetPeriod.YEAR
                            )
                            .usageLimit(0.0)
                            .weeklyResetPeriodConfiguration(
                                SetPackagePricing.OveragePricingModel.Entitlement
                                    .WeeklyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        SetPackagePricing.OveragePricingModel.Entitlement
                                            .WeeklyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .yearlyResetPeriodConfiguration(
                                SetPackagePricing.OveragePricingModel.Entitlement
                                    .YearlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        SetPackagePricing.OveragePricingModel.Entitlement
                                            .YearlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .featureId("featureId")
                    .topUpCustomCurrencyId("topUpCustomCurrencyId")
                    .build()
            )
        assertThat(setPackagePricing.pricingModels().getOrNull())
            .containsExactly(
                SetPackagePricing.PricingModel.builder()
                    .billingModel(SetPackagePricing.PricingModel.BillingModel.FLAT_FEE)
                    .addPricePeriod(
                        SetPackagePricing.PricingModel.PricePeriod.builder()
                            .billingPeriod(
                                SetPackagePricing.PricingModel.PricePeriod.BillingPeriod.MONTHLY
                            )
                            .billingCountryCode("billingCountryCode")
                            .blockSize(0.0)
                            .creditGrantCadence(
                                SetPackagePricing.PricingModel.PricePeriod.CreditGrantCadence
                                    .BEGINNING_OF_BILLING_PERIOD
                            )
                            .creditRate(
                                SetPackagePricing.PricingModel.PricePeriod.CreditRate.builder()
                                    .amount(1.0)
                                    .currencyId("currencyId")
                                    .costFormula("costFormula")
                                    .build()
                            )
                            .price(
                                SetPackagePricing.PricingModel.PricePeriod.Price.builder()
                                    .amount(0.0)
                                    .currency(
                                        SetPackagePricing.PricingModel.PricePeriod.Price.Currency
                                            .USD
                                    )
                                    .build()
                            )
                            .addTier(
                                SetPackagePricing.PricingModel.PricePeriod.Tier.builder()
                                    .flatPrice(
                                        SetPackagePricing.PricingModel.PricePeriod.Tier.FlatPrice
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                SetPackagePricing.PricingModel.PricePeriod.Tier
                                                    .FlatPrice
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .unitPrice(
                                        SetPackagePricing.PricingModel.PricePeriod.Tier.UnitPrice
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                SetPackagePricing.PricingModel.PricePeriod.Tier
                                                    .UnitPrice
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .upTo(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .billingCadence(SetPackagePricing.PricingModel.BillingCadence.RECURRING)
                    .featureId("featureId")
                    .maxUnitQuantity(1L)
                    .minUnitQuantity(1L)
                    .monthlyResetPeriodConfiguration(
                        SetPackagePricing.PricingModel.MonthlyResetPeriodConfiguration.builder()
                            .accordingTo(
                                SetPackagePricing.PricingModel.MonthlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .resetPeriod(SetPackagePricing.PricingModel.ResetPeriod.YEAR)
                    .tiersMode(SetPackagePricing.PricingModel.TiersMode.VOLUME)
                    .topUpCustomCurrencyId("topUpCustomCurrencyId")
                    .weeklyResetPeriodConfiguration(
                        SetPackagePricing.PricingModel.WeeklyResetPeriodConfiguration.builder()
                            .accordingTo(
                                SetPackagePricing.PricingModel.WeeklyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .yearlyResetPeriodConfiguration(
                        SetPackagePricing.PricingModel.YearlyResetPeriodConfiguration.builder()
                            .accordingTo(
                                SetPackagePricing.PricingModel.YearlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val setPackagePricing =
            SetPackagePricing.builder()
                .pricingType(SetPackagePricing.PricingType.FREE)
                .billingId("billingId")
                .addMinimumSpend(
                    SetPackagePricing.MinimumSpend.builder()
                        .billingPeriod(SetPackagePricing.MinimumSpend.BillingPeriod.MONTHLY)
                        .minimum(
                            SetPackagePricing.MinimumSpend.Minimum.builder()
                                .amount(0.0)
                                .currency(SetPackagePricing.MinimumSpend.Minimum.Currency.USD)
                                .build()
                        )
                        .build()
                )
                .overageBillingPeriod(
                    SetPackagePricing.OverageBillingPeriod.ON_SUBSCRIPTION_RENEWAL
                )
                .addOveragePricingModel(
                    SetPackagePricing.OveragePricingModel.builder()
                        .billingModel(SetPackagePricing.OveragePricingModel.BillingModel.FLAT_FEE)
                        .addPricePeriod(
                            SetPackagePricing.OveragePricingModel.PricePeriod.builder()
                                .billingPeriod(
                                    SetPackagePricing.OveragePricingModel.PricePeriod.BillingPeriod
                                        .MONTHLY
                                )
                                .billingCountryCode("billingCountryCode")
                                .blockSize(0.0)
                                .creditGrantCadence(
                                    SetPackagePricing.OveragePricingModel.PricePeriod
                                        .CreditGrantCadence
                                        .BEGINNING_OF_BILLING_PERIOD
                                )
                                .creditRate(
                                    SetPackagePricing.OveragePricingModel.PricePeriod.CreditRate
                                        .builder()
                                        .amount(1.0)
                                        .currencyId("currencyId")
                                        .costFormula("costFormula")
                                        .build()
                                )
                                .price(
                                    SetPackagePricing.OveragePricingModel.PricePeriod.Price
                                        .builder()
                                        .amount(0.0)
                                        .currency(
                                            SetPackagePricing.OveragePricingModel.PricePeriod.Price
                                                .Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .addTier(
                                    SetPackagePricing.OveragePricingModel.PricePeriod.Tier.builder()
                                        .flatPrice(
                                            SetPackagePricing.OveragePricingModel.PricePeriod.Tier
                                                .FlatPrice
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SetPackagePricing.OveragePricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .FlatPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .unitPrice(
                                            SetPackagePricing.OveragePricingModel.PricePeriod.Tier
                                                .UnitPrice
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SetPackagePricing.OveragePricingModel
                                                        .PricePeriod
                                                        .Tier
                                                        .UnitPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .upTo(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .billingCadence(
                            SetPackagePricing.OveragePricingModel.BillingCadence.RECURRING
                        )
                        .entitlement(
                            SetPackagePricing.OveragePricingModel.Entitlement.builder()
                                .featureId("featureId")
                                .hasSoftLimit(true)
                                .hasUnlimitedUsage(true)
                                .monthlyResetPeriodConfiguration(
                                    SetPackagePricing.OveragePricingModel.Entitlement
                                        .MonthlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            SetPackagePricing.OveragePricingModel.Entitlement
                                                .MonthlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .resetPeriod(
                                    SetPackagePricing.OveragePricingModel.Entitlement.ResetPeriod
                                        .YEAR
                                )
                                .usageLimit(0.0)
                                .weeklyResetPeriodConfiguration(
                                    SetPackagePricing.OveragePricingModel.Entitlement
                                        .WeeklyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            SetPackagePricing.OveragePricingModel.Entitlement
                                                .WeeklyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .yearlyResetPeriodConfiguration(
                                    SetPackagePricing.OveragePricingModel.Entitlement
                                        .YearlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            SetPackagePricing.OveragePricingModel.Entitlement
                                                .YearlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .featureId("featureId")
                        .topUpCustomCurrencyId("topUpCustomCurrencyId")
                        .build()
                )
                .addPricingModel(
                    SetPackagePricing.PricingModel.builder()
                        .billingModel(SetPackagePricing.PricingModel.BillingModel.FLAT_FEE)
                        .addPricePeriod(
                            SetPackagePricing.PricingModel.PricePeriod.builder()
                                .billingPeriod(
                                    SetPackagePricing.PricingModel.PricePeriod.BillingPeriod.MONTHLY
                                )
                                .billingCountryCode("billingCountryCode")
                                .blockSize(0.0)
                                .creditGrantCadence(
                                    SetPackagePricing.PricingModel.PricePeriod.CreditGrantCadence
                                        .BEGINNING_OF_BILLING_PERIOD
                                )
                                .creditRate(
                                    SetPackagePricing.PricingModel.PricePeriod.CreditRate.builder()
                                        .amount(1.0)
                                        .currencyId("currencyId")
                                        .costFormula("costFormula")
                                        .build()
                                )
                                .price(
                                    SetPackagePricing.PricingModel.PricePeriod.Price.builder()
                                        .amount(0.0)
                                        .currency(
                                            SetPackagePricing.PricingModel.PricePeriod.Price
                                                .Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .addTier(
                                    SetPackagePricing.PricingModel.PricePeriod.Tier.builder()
                                        .flatPrice(
                                            SetPackagePricing.PricingModel.PricePeriod.Tier
                                                .FlatPrice
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SetPackagePricing.PricingModel.PricePeriod.Tier
                                                        .FlatPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .unitPrice(
                                            SetPackagePricing.PricingModel.PricePeriod.Tier
                                                .UnitPrice
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SetPackagePricing.PricingModel.PricePeriod.Tier
                                                        .UnitPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .upTo(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .billingCadence(SetPackagePricing.PricingModel.BillingCadence.RECURRING)
                        .featureId("featureId")
                        .maxUnitQuantity(1L)
                        .minUnitQuantity(1L)
                        .monthlyResetPeriodConfiguration(
                            SetPackagePricing.PricingModel.MonthlyResetPeriodConfiguration.builder()
                                .accordingTo(
                                    SetPackagePricing.PricingModel.MonthlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .resetPeriod(SetPackagePricing.PricingModel.ResetPeriod.YEAR)
                        .tiersMode(SetPackagePricing.PricingModel.TiersMode.VOLUME)
                        .topUpCustomCurrencyId("topUpCustomCurrencyId")
                        .weeklyResetPeriodConfiguration(
                            SetPackagePricing.PricingModel.WeeklyResetPeriodConfiguration.builder()
                                .accordingTo(
                                    SetPackagePricing.PricingModel.WeeklyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .yearlyResetPeriodConfiguration(
                            SetPackagePricing.PricingModel.YearlyResetPeriodConfiguration.builder()
                                .accordingTo(
                                    SetPackagePricing.PricingModel.YearlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedSetPackagePricing =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(setPackagePricing),
                jacksonTypeRef<SetPackagePricing>(),
            )

        assertThat(roundtrippedSetPackagePricing).isEqualTo(setPackagePricing)
    }
}
