// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.customers.promotionalentitlements

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PromotionalEntitlementGrantParamsTest {

    @Test
    fun create() {
        PromotionalEntitlementGrantParams.builder()
            .customerId("customerId")
            .addPromotionalEntitlement(
                PromotionalEntitlementGrantParams.PromotionalEntitlement.builder()
                    .customEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addEnumValue("string")
                    .featureId("featureId")
                    .hasSoftLimit(true)
                    .hasUnlimitedUsage(true)
                    .isVisible(true)
                    .monthlyResetPeriodConfiguration(
                        PromotionalEntitlementGrantParams.PromotionalEntitlement
                            .MonthlyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                PromotionalEntitlementGrantParams.PromotionalEntitlement
                                    .MonthlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .period(PromotionalEntitlementGrantParams.PromotionalEntitlement.Period._1_WEEK)
                    .resetPeriod(
                        PromotionalEntitlementGrantParams.PromotionalEntitlement.ResetPeriod.YEAR
                    )
                    .usageLimit(-9007199254740991L)
                    .weeklyResetPeriodConfiguration(
                        PromotionalEntitlementGrantParams.PromotionalEntitlement
                            .WeeklyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                PromotionalEntitlementGrantParams.PromotionalEntitlement
                                    .WeeklyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .yearlyResetPeriodConfiguration(
                        PromotionalEntitlementGrantParams.PromotionalEntitlement
                            .YearlyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                PromotionalEntitlementGrantParams.PromotionalEntitlement
                                    .YearlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .build()
            )
            .build()
    }

    @Test
    fun pathParams() {
        val params =
            PromotionalEntitlementGrantParams.builder()
                .customerId("customerId")
                .addPromotionalEntitlement(
                    PromotionalEntitlementGrantParams.PromotionalEntitlement.builder()
                        .customEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addEnumValue("string")
                        .featureId("featureId")
                        .hasSoftLimit(true)
                        .hasUnlimitedUsage(true)
                        .isVisible(true)
                        .monthlyResetPeriodConfiguration(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement
                                .MonthlyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    PromotionalEntitlementGrantParams.PromotionalEntitlement
                                        .MonthlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .period(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement.Period._1_WEEK
                        )
                        .resetPeriod(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement.ResetPeriod
                                .YEAR
                        )
                        .usageLimit(-9007199254740991L)
                        .weeklyResetPeriodConfiguration(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement
                                .WeeklyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    PromotionalEntitlementGrantParams.PromotionalEntitlement
                                        .WeeklyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .yearlyResetPeriodConfiguration(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement
                                .YearlyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    PromotionalEntitlementGrantParams.PromotionalEntitlement
                                        .YearlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(params._pathParam(0)).isEqualTo("customerId")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            PromotionalEntitlementGrantParams.builder()
                .customerId("customerId")
                .addPromotionalEntitlement(
                    PromotionalEntitlementGrantParams.PromotionalEntitlement.builder()
                        .customEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addEnumValue("string")
                        .featureId("featureId")
                        .hasSoftLimit(true)
                        .hasUnlimitedUsage(true)
                        .isVisible(true)
                        .monthlyResetPeriodConfiguration(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement
                                .MonthlyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    PromotionalEntitlementGrantParams.PromotionalEntitlement
                                        .MonthlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .period(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement.Period._1_WEEK
                        )
                        .resetPeriod(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement.ResetPeriod
                                .YEAR
                        )
                        .usageLimit(-9007199254740991L)
                        .weeklyResetPeriodConfiguration(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement
                                .WeeklyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    PromotionalEntitlementGrantParams.PromotionalEntitlement
                                        .WeeklyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .yearlyResetPeriodConfiguration(
                            PromotionalEntitlementGrantParams.PromotionalEntitlement
                                .YearlyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    PromotionalEntitlementGrantParams.PromotionalEntitlement
                                        .YearlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.promotionalEntitlements())
            .containsExactly(
                PromotionalEntitlementGrantParams.PromotionalEntitlement.builder()
                    .customEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addEnumValue("string")
                    .featureId("featureId")
                    .hasSoftLimit(true)
                    .hasUnlimitedUsage(true)
                    .isVisible(true)
                    .monthlyResetPeriodConfiguration(
                        PromotionalEntitlementGrantParams.PromotionalEntitlement
                            .MonthlyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                PromotionalEntitlementGrantParams.PromotionalEntitlement
                                    .MonthlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .period(PromotionalEntitlementGrantParams.PromotionalEntitlement.Period._1_WEEK)
                    .resetPeriod(
                        PromotionalEntitlementGrantParams.PromotionalEntitlement.ResetPeriod.YEAR
                    )
                    .usageLimit(-9007199254740991L)
                    .weeklyResetPeriodConfiguration(
                        PromotionalEntitlementGrantParams.PromotionalEntitlement
                            .WeeklyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                PromotionalEntitlementGrantParams.PromotionalEntitlement
                                    .WeeklyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .yearlyResetPeriodConfiguration(
                        PromotionalEntitlementGrantParams.PromotionalEntitlement
                            .YearlyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                PromotionalEntitlementGrantParams.PromotionalEntitlement
                                    .YearlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .build()
            )
    }
}
