// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.plans.entitlements

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EntitlementCreateParamsTest {

    @Test
    fun create() {
        EntitlementCreateParams.builder()
            .planId("planId")
            .addEntitlement(
                EntitlementCreateParams.Entitlement.builder()
                    .credit(
                        EntitlementCreateParams.Entitlement.Credit.builder()
                            .amount(1.0)
                            .cadence(EntitlementCreateParams.Entitlement.Credit.Cadence.MONTH)
                            .customCurrencyId("customCurrencyId")
                            .behavior(EntitlementCreateParams.Entitlement.Credit.Behavior.INCREMENT)
                            .description("description")
                            .displayNameOverride("displayNameOverride")
                            .addHiddenFromWidget(
                                EntitlementCreateParams.Entitlement.Credit.HiddenFromWidget.PAYWALL
                            )
                            .isCustom(true)
                            .isGranted(true)
                            .order(0.0)
                            .build()
                    )
                    .feature(
                        EntitlementCreateParams.Entitlement.Feature.builder()
                            .featureId("featureId")
                            .behavior(
                                EntitlementCreateParams.Entitlement.Feature.Behavior.INCREMENT
                            )
                            .description("description")
                            .displayNameOverride("displayNameOverride")
                            .addEnumValue("string")
                            .hasSoftLimit(true)
                            .hasUnlimitedUsage(true)
                            .addHiddenFromWidget(
                                EntitlementCreateParams.Entitlement.Feature.HiddenFromWidget.PAYWALL
                            )
                            .isCustom(true)
                            .isGranted(true)
                            .monthlyResetPeriodConfiguration(
                                EntitlementCreateParams.Entitlement.Feature
                                    .MonthlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        EntitlementCreateParams.Entitlement.Feature
                                            .MonthlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .order(0.0)
                            .resetPeriod(
                                EntitlementCreateParams.Entitlement.Feature.ResetPeriod.YEAR
                            )
                            .usageLimit(0L)
                            .weeklyResetPeriodConfiguration(
                                EntitlementCreateParams.Entitlement.Feature
                                    .WeeklyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        EntitlementCreateParams.Entitlement.Feature
                                            .WeeklyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .yearlyResetPeriodConfiguration(
                                EntitlementCreateParams.Entitlement.Feature
                                    .YearlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        EntitlementCreateParams.Entitlement.Feature
                                            .YearlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
            .build()
    }

    @Test
    fun pathParams() {
        val params =
            EntitlementCreateParams.builder()
                .planId("planId")
                .addEntitlement(EntitlementCreateParams.Entitlement.builder().build())
                .build()

        assertThat(params._pathParam(0)).isEqualTo("planId")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            EntitlementCreateParams.builder()
                .planId("planId")
                .addEntitlement(
                    EntitlementCreateParams.Entitlement.builder()
                        .credit(
                            EntitlementCreateParams.Entitlement.Credit.builder()
                                .amount(1.0)
                                .cadence(EntitlementCreateParams.Entitlement.Credit.Cadence.MONTH)
                                .customCurrencyId("customCurrencyId")
                                .behavior(
                                    EntitlementCreateParams.Entitlement.Credit.Behavior.INCREMENT
                                )
                                .description("description")
                                .displayNameOverride("displayNameOverride")
                                .addHiddenFromWidget(
                                    EntitlementCreateParams.Entitlement.Credit.HiddenFromWidget
                                        .PAYWALL
                                )
                                .isCustom(true)
                                .isGranted(true)
                                .order(0.0)
                                .build()
                        )
                        .feature(
                            EntitlementCreateParams.Entitlement.Feature.builder()
                                .featureId("featureId")
                                .behavior(
                                    EntitlementCreateParams.Entitlement.Feature.Behavior.INCREMENT
                                )
                                .description("description")
                                .displayNameOverride("displayNameOverride")
                                .addEnumValue("string")
                                .hasSoftLimit(true)
                                .hasUnlimitedUsage(true)
                                .addHiddenFromWidget(
                                    EntitlementCreateParams.Entitlement.Feature.HiddenFromWidget
                                        .PAYWALL
                                )
                                .isCustom(true)
                                .isGranted(true)
                                .monthlyResetPeriodConfiguration(
                                    EntitlementCreateParams.Entitlement.Feature
                                        .MonthlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            EntitlementCreateParams.Entitlement.Feature
                                                .MonthlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .order(0.0)
                                .resetPeriod(
                                    EntitlementCreateParams.Entitlement.Feature.ResetPeriod.YEAR
                                )
                                .usageLimit(0L)
                                .weeklyResetPeriodConfiguration(
                                    EntitlementCreateParams.Entitlement.Feature
                                        .WeeklyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            EntitlementCreateParams.Entitlement.Feature
                                                .WeeklyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .yearlyResetPeriodConfiguration(
                                    EntitlementCreateParams.Entitlement.Feature
                                        .YearlyResetPeriodConfiguration
                                        .builder()
                                        .accordingTo(
                                            EntitlementCreateParams.Entitlement.Feature
                                                .YearlyResetPeriodConfiguration
                                                .AccordingTo
                                                .SUBSCRIPTION_START
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body.entitlements())
            .containsExactly(
                EntitlementCreateParams.Entitlement.builder()
                    .credit(
                        EntitlementCreateParams.Entitlement.Credit.builder()
                            .amount(1.0)
                            .cadence(EntitlementCreateParams.Entitlement.Credit.Cadence.MONTH)
                            .customCurrencyId("customCurrencyId")
                            .behavior(EntitlementCreateParams.Entitlement.Credit.Behavior.INCREMENT)
                            .description("description")
                            .displayNameOverride("displayNameOverride")
                            .addHiddenFromWidget(
                                EntitlementCreateParams.Entitlement.Credit.HiddenFromWidget.PAYWALL
                            )
                            .isCustom(true)
                            .isGranted(true)
                            .order(0.0)
                            .build()
                    )
                    .feature(
                        EntitlementCreateParams.Entitlement.Feature.builder()
                            .featureId("featureId")
                            .behavior(
                                EntitlementCreateParams.Entitlement.Feature.Behavior.INCREMENT
                            )
                            .description("description")
                            .displayNameOverride("displayNameOverride")
                            .addEnumValue("string")
                            .hasSoftLimit(true)
                            .hasUnlimitedUsage(true)
                            .addHiddenFromWidget(
                                EntitlementCreateParams.Entitlement.Feature.HiddenFromWidget.PAYWALL
                            )
                            .isCustom(true)
                            .isGranted(true)
                            .monthlyResetPeriodConfiguration(
                                EntitlementCreateParams.Entitlement.Feature
                                    .MonthlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        EntitlementCreateParams.Entitlement.Feature
                                            .MonthlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .order(0.0)
                            .resetPeriod(
                                EntitlementCreateParams.Entitlement.Feature.ResetPeriod.YEAR
                            )
                            .usageLimit(0L)
                            .weeklyResetPeriodConfiguration(
                                EntitlementCreateParams.Entitlement.Feature
                                    .WeeklyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        EntitlementCreateParams.Entitlement.Feature
                                            .WeeklyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .yearlyResetPeriodConfiguration(
                                EntitlementCreateParams.Entitlement.Feature
                                    .YearlyResetPeriodConfiguration
                                    .builder()
                                    .accordingTo(
                                        EntitlementCreateParams.Entitlement.Feature
                                            .YearlyResetPeriodConfiguration
                                            .AccordingTo
                                            .SUBSCRIPTION_START
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            EntitlementCreateParams.builder()
                .planId("planId")
                .addEntitlement(EntitlementCreateParams.Entitlement.builder().build())
                .build()

        val body = params._body()

        assertThat(body.entitlements())
            .containsExactly(EntitlementCreateParams.Entitlement.builder().build())
    }
}
