// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.plans

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.stigg.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PlanListOverageChargesPageResponseTest {

    @Test
    fun create() {
        val planListOverageChargesPageResponse =
            PlanListOverageChargesPageResponse.builder()
                .addData(
                    PlanListOverageChargesResponse.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .billingCadence(PlanListOverageChargesResponse.BillingCadence.RECURRING)
                        .billingModel(PlanListOverageChargesResponse.BillingModel.FLAT_FEE)
                        .billingPeriod(PlanListOverageChargesResponse.BillingPeriod.MONTHLY)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .billingCountryCode("billingCountryCode")
                        .billingId("billingId")
                        .blockSize(0.0)
                        .creditGrantCadence(
                            PlanListOverageChargesResponse.CreditGrantCadence
                                .BEGINNING_OF_BILLING_PERIOD
                        )
                        .creditRate(
                            PlanListOverageChargesResponse.CreditRate.builder()
                                .amount(0.0)
                                .currencyId("currencyId")
                                .costFormula("costFormula")
                                .build()
                        )
                        .crmId("crmId")
                        .crmLinkUrl("crmLinkUrl")
                        .featureId("featureId")
                        .maxUnitQuantity(0.0)
                        .minUnitQuantity(0.0)
                        .price(
                            PlanListOverageChargesResponse.Price.builder()
                                .amount(0.0)
                                .currency(PlanListOverageChargesResponse.Price.Currency.USD)
                                .build()
                        )
                        .addTier(
                            PlanListOverageChargesResponse.Tier.builder()
                                .flatPrice(
                                    PlanListOverageChargesResponse.Tier.FlatPrice.builder()
                                        .amount(0.0)
                                        .currency(
                                            PlanListOverageChargesResponse.Tier.FlatPrice.Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .unitPrice(
                                    PlanListOverageChargesResponse.Tier.UnitPrice.builder()
                                        .amount(0.0)
                                        .currency(
                                            PlanListOverageChargesResponse.Tier.UnitPrice.Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .upTo(0.0)
                                .build()
                        )
                        .tiersMode(PlanListOverageChargesResponse.TiersMode.VOLUME)
                        .topUpCustomCurrencyId("topUpCustomCurrencyId")
                        .usedInSubscriptions(true)
                        .build()
                )
                .pagination(
                    PlanListOverageChargesPageResponse.Pagination.builder()
                        .next("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .prev("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        assertThat(planListOverageChargesPageResponse.data())
            .containsExactly(
                PlanListOverageChargesResponse.builder()
                    .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .billingCadence(PlanListOverageChargesResponse.BillingCadence.RECURRING)
                    .billingModel(PlanListOverageChargesResponse.BillingModel.FLAT_FEE)
                    .billingPeriod(PlanListOverageChargesResponse.BillingPeriod.MONTHLY)
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .billingCountryCode("billingCountryCode")
                    .billingId("billingId")
                    .blockSize(0.0)
                    .creditGrantCadence(
                        PlanListOverageChargesResponse.CreditGrantCadence
                            .BEGINNING_OF_BILLING_PERIOD
                    )
                    .creditRate(
                        PlanListOverageChargesResponse.CreditRate.builder()
                            .amount(0.0)
                            .currencyId("currencyId")
                            .costFormula("costFormula")
                            .build()
                    )
                    .crmId("crmId")
                    .crmLinkUrl("crmLinkUrl")
                    .featureId("featureId")
                    .maxUnitQuantity(0.0)
                    .minUnitQuantity(0.0)
                    .price(
                        PlanListOverageChargesResponse.Price.builder()
                            .amount(0.0)
                            .currency(PlanListOverageChargesResponse.Price.Currency.USD)
                            .build()
                    )
                    .addTier(
                        PlanListOverageChargesResponse.Tier.builder()
                            .flatPrice(
                                PlanListOverageChargesResponse.Tier.FlatPrice.builder()
                                    .amount(0.0)
                                    .currency(
                                        PlanListOverageChargesResponse.Tier.FlatPrice.Currency.USD
                                    )
                                    .build()
                            )
                            .unitPrice(
                                PlanListOverageChargesResponse.Tier.UnitPrice.builder()
                                    .amount(0.0)
                                    .currency(
                                        PlanListOverageChargesResponse.Tier.UnitPrice.Currency.USD
                                    )
                                    .build()
                            )
                            .upTo(0.0)
                            .build()
                    )
                    .tiersMode(PlanListOverageChargesResponse.TiersMode.VOLUME)
                    .topUpCustomCurrencyId("topUpCustomCurrencyId")
                    .usedInSubscriptions(true)
                    .build()
            )
        assertThat(planListOverageChargesPageResponse.pagination())
            .isEqualTo(
                PlanListOverageChargesPageResponse.Pagination.builder()
                    .next("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .prev("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val planListOverageChargesPageResponse =
            PlanListOverageChargesPageResponse.builder()
                .addData(
                    PlanListOverageChargesResponse.builder()
                        .id("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .billingCadence(PlanListOverageChargesResponse.BillingCadence.RECURRING)
                        .billingModel(PlanListOverageChargesResponse.BillingModel.FLAT_FEE)
                        .billingPeriod(PlanListOverageChargesResponse.BillingPeriod.MONTHLY)
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .billingCountryCode("billingCountryCode")
                        .billingId("billingId")
                        .blockSize(0.0)
                        .creditGrantCadence(
                            PlanListOverageChargesResponse.CreditGrantCadence
                                .BEGINNING_OF_BILLING_PERIOD
                        )
                        .creditRate(
                            PlanListOverageChargesResponse.CreditRate.builder()
                                .amount(0.0)
                                .currencyId("currencyId")
                                .costFormula("costFormula")
                                .build()
                        )
                        .crmId("crmId")
                        .crmLinkUrl("crmLinkUrl")
                        .featureId("featureId")
                        .maxUnitQuantity(0.0)
                        .minUnitQuantity(0.0)
                        .price(
                            PlanListOverageChargesResponse.Price.builder()
                                .amount(0.0)
                                .currency(PlanListOverageChargesResponse.Price.Currency.USD)
                                .build()
                        )
                        .addTier(
                            PlanListOverageChargesResponse.Tier.builder()
                                .flatPrice(
                                    PlanListOverageChargesResponse.Tier.FlatPrice.builder()
                                        .amount(0.0)
                                        .currency(
                                            PlanListOverageChargesResponse.Tier.FlatPrice.Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .unitPrice(
                                    PlanListOverageChargesResponse.Tier.UnitPrice.builder()
                                        .amount(0.0)
                                        .currency(
                                            PlanListOverageChargesResponse.Tier.UnitPrice.Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .upTo(0.0)
                                .build()
                        )
                        .tiersMode(PlanListOverageChargesResponse.TiersMode.VOLUME)
                        .topUpCustomCurrencyId("topUpCustomCurrencyId")
                        .usedInSubscriptions(true)
                        .build()
                )
                .pagination(
                    PlanListOverageChargesPageResponse.Pagination.builder()
                        .next("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .prev("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        val roundtrippedPlanListOverageChargesPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(planListOverageChargesPageResponse),
                jacksonTypeRef<PlanListOverageChargesPageResponse>(),
            )

        assertThat(roundtrippedPlanListOverageChargesPageResponse)
            .isEqualTo(planListOverageChargesPageResponse)
    }
}
