// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.subscriptions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.stigg.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SubscriptionPreviewResponseTest {

    @Test
    fun create() {
        val subscriptionPreviewResponse =
            SubscriptionPreviewResponse.builder()
                .data(
                    SubscriptionPreviewResponse.Data.builder()
                        .immediateInvoice(
                            SubscriptionPreviewResponse.Data.ImmediateInvoice.builder()
                                .subTotal(0.0)
                                .total(0.0)
                                .billingPeriodRange(
                                    SubscriptionPreviewResponse.Data.ImmediateInvoice
                                        .BillingPeriodRange
                                        .builder()
                                        .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .currency("currency")
                                .discount(0.0)
                                .discountDetails(
                                    SubscriptionPreviewResponse.Data.ImmediateInvoice
                                        .DiscountDetails
                                        .builder()
                                        .code("code")
                                        .fixedAmount(0.0)
                                        .percentage(0.0)
                                        .build()
                                )
                                .addDiscount(
                                    SubscriptionPreviewResponse.Data.ImmediateInvoice.Discount
                                        .builder()
                                        .amount(0.0)
                                        .currency("currency")
                                        .description("description")
                                        .build()
                                )
                                .addLine(
                                    SubscriptionPreviewResponse.Data.ImmediateInvoice.Line.builder()
                                        .currency("currency")
                                        .description("description")
                                        .subTotal(0.0)
                                        .unitPrice(0.0)
                                        .quantity(0.0)
                                        .build()
                                )
                                .tax(0.0)
                                .build()
                        )
                        .billingPeriodRange(
                            SubscriptionPreviewResponse.Data.BillingPeriodRange.builder()
                                .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .addFreeItem(
                            SubscriptionPreviewResponse.Data.FreeItem.builder()
                                .addonId("addonId")
                                .quantity(0.0)
                                .build()
                        )
                        .hasScheduledUpdates(true)
                        .isPlanDowngrade(true)
                        .recurringInvoice(
                            SubscriptionPreviewResponse.Data.RecurringInvoice.builder()
                                .subTotal(0.0)
                                .total(0.0)
                                .billingPeriodRange(
                                    SubscriptionPreviewResponse.Data.RecurringInvoice
                                        .BillingPeriodRange
                                        .builder()
                                        .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .currency("currency")
                                .discount(0.0)
                                .discountDetails(
                                    SubscriptionPreviewResponse.Data.RecurringInvoice
                                        .DiscountDetails
                                        .builder()
                                        .code("code")
                                        .fixedAmount(0.0)
                                        .percentage(0.0)
                                        .build()
                                )
                                .addDiscount(
                                    SubscriptionPreviewResponse.Data.RecurringInvoice.Discount
                                        .builder()
                                        .amount(0.0)
                                        .currency("currency")
                                        .description("description")
                                        .build()
                                )
                                .addLine(
                                    SubscriptionPreviewResponse.Data.RecurringInvoice.Line.builder()
                                        .currency("currency")
                                        .description("description")
                                        .subTotal(0.0)
                                        .unitPrice(0.0)
                                        .quantity(0.0)
                                        .build()
                                )
                                .tax(0.0)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(subscriptionPreviewResponse.data())
            .isEqualTo(
                SubscriptionPreviewResponse.Data.builder()
                    .immediateInvoice(
                        SubscriptionPreviewResponse.Data.ImmediateInvoice.builder()
                            .subTotal(0.0)
                            .total(0.0)
                            .billingPeriodRange(
                                SubscriptionPreviewResponse.Data.ImmediateInvoice.BillingPeriodRange
                                    .builder()
                                    .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .currency("currency")
                            .discount(0.0)
                            .discountDetails(
                                SubscriptionPreviewResponse.Data.ImmediateInvoice.DiscountDetails
                                    .builder()
                                    .code("code")
                                    .fixedAmount(0.0)
                                    .percentage(0.0)
                                    .build()
                            )
                            .addDiscount(
                                SubscriptionPreviewResponse.Data.ImmediateInvoice.Discount.builder()
                                    .amount(0.0)
                                    .currency("currency")
                                    .description("description")
                                    .build()
                            )
                            .addLine(
                                SubscriptionPreviewResponse.Data.ImmediateInvoice.Line.builder()
                                    .currency("currency")
                                    .description("description")
                                    .subTotal(0.0)
                                    .unitPrice(0.0)
                                    .quantity(0.0)
                                    .build()
                            )
                            .tax(0.0)
                            .build()
                    )
                    .billingPeriodRange(
                        SubscriptionPreviewResponse.Data.BillingPeriodRange.builder()
                            .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .addFreeItem(
                        SubscriptionPreviewResponse.Data.FreeItem.builder()
                            .addonId("addonId")
                            .quantity(0.0)
                            .build()
                    )
                    .hasScheduledUpdates(true)
                    .isPlanDowngrade(true)
                    .recurringInvoice(
                        SubscriptionPreviewResponse.Data.RecurringInvoice.builder()
                            .subTotal(0.0)
                            .total(0.0)
                            .billingPeriodRange(
                                SubscriptionPreviewResponse.Data.RecurringInvoice.BillingPeriodRange
                                    .builder()
                                    .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .build()
                            )
                            .currency("currency")
                            .discount(0.0)
                            .discountDetails(
                                SubscriptionPreviewResponse.Data.RecurringInvoice.DiscountDetails
                                    .builder()
                                    .code("code")
                                    .fixedAmount(0.0)
                                    .percentage(0.0)
                                    .build()
                            )
                            .addDiscount(
                                SubscriptionPreviewResponse.Data.RecurringInvoice.Discount.builder()
                                    .amount(0.0)
                                    .currency("currency")
                                    .description("description")
                                    .build()
                            )
                            .addLine(
                                SubscriptionPreviewResponse.Data.RecurringInvoice.Line.builder()
                                    .currency("currency")
                                    .description("description")
                                    .subTotal(0.0)
                                    .unitPrice(0.0)
                                    .quantity(0.0)
                                    .build()
                            )
                            .tax(0.0)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val subscriptionPreviewResponse =
            SubscriptionPreviewResponse.builder()
                .data(
                    SubscriptionPreviewResponse.Data.builder()
                        .immediateInvoice(
                            SubscriptionPreviewResponse.Data.ImmediateInvoice.builder()
                                .subTotal(0.0)
                                .total(0.0)
                                .billingPeriodRange(
                                    SubscriptionPreviewResponse.Data.ImmediateInvoice
                                        .BillingPeriodRange
                                        .builder()
                                        .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .currency("currency")
                                .discount(0.0)
                                .discountDetails(
                                    SubscriptionPreviewResponse.Data.ImmediateInvoice
                                        .DiscountDetails
                                        .builder()
                                        .code("code")
                                        .fixedAmount(0.0)
                                        .percentage(0.0)
                                        .build()
                                )
                                .addDiscount(
                                    SubscriptionPreviewResponse.Data.ImmediateInvoice.Discount
                                        .builder()
                                        .amount(0.0)
                                        .currency("currency")
                                        .description("description")
                                        .build()
                                )
                                .addLine(
                                    SubscriptionPreviewResponse.Data.ImmediateInvoice.Line.builder()
                                        .currency("currency")
                                        .description("description")
                                        .subTotal(0.0)
                                        .unitPrice(0.0)
                                        .quantity(0.0)
                                        .build()
                                )
                                .tax(0.0)
                                .build()
                        )
                        .billingPeriodRange(
                            SubscriptionPreviewResponse.Data.BillingPeriodRange.builder()
                                .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .addFreeItem(
                            SubscriptionPreviewResponse.Data.FreeItem.builder()
                                .addonId("addonId")
                                .quantity(0.0)
                                .build()
                        )
                        .hasScheduledUpdates(true)
                        .isPlanDowngrade(true)
                        .recurringInvoice(
                            SubscriptionPreviewResponse.Data.RecurringInvoice.builder()
                                .subTotal(0.0)
                                .total(0.0)
                                .billingPeriodRange(
                                    SubscriptionPreviewResponse.Data.RecurringInvoice
                                        .BillingPeriodRange
                                        .builder()
                                        .end(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .start(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .build()
                                )
                                .currency("currency")
                                .discount(0.0)
                                .discountDetails(
                                    SubscriptionPreviewResponse.Data.RecurringInvoice
                                        .DiscountDetails
                                        .builder()
                                        .code("code")
                                        .fixedAmount(0.0)
                                        .percentage(0.0)
                                        .build()
                                )
                                .addDiscount(
                                    SubscriptionPreviewResponse.Data.RecurringInvoice.Discount
                                        .builder()
                                        .amount(0.0)
                                        .currency("currency")
                                        .description("description")
                                        .build()
                                )
                                .addLine(
                                    SubscriptionPreviewResponse.Data.RecurringInvoice.Line.builder()
                                        .currency("currency")
                                        .description("description")
                                        .subTotal(0.0)
                                        .unitPrice(0.0)
                                        .quantity(0.0)
                                        .build()
                                )
                                .tax(0.0)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedSubscriptionPreviewResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(subscriptionPreviewResponse),
                jacksonTypeRef<SubscriptionPreviewResponse>(),
            )

        assertThat(roundtrippedSubscriptionPreviewResponse).isEqualTo(subscriptionPreviewResponse)
    }
}
