// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.subscriptions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.stigg.core.JsonValue
import io.stigg.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SubscriptionProvisionResponseTest {

    @Test
    fun create() {
        val subscriptionProvisionResponse =
            SubscriptionProvisionResponse.builder()
                .data(
                    SubscriptionProvisionResponse.Data.builder()
                        .id("id")
                        .addEntitlement(
                            SubscriptionProvisionResponse.Data.Entitlement.UnionObjectVariant0
                                .builder()
                                .accessDeniedReason(
                                    SubscriptionProvisionResponse.Data.Entitlement
                                        .UnionObjectVariant0
                                        .AccessDeniedReason
                                        .FEATURE_NOT_FOUND
                                )
                                .isGranted(true)
                                .type(
                                    SubscriptionProvisionResponse.Data.Entitlement
                                        .UnionObjectVariant0
                                        .Type
                                        .FEATURE
                                )
                                .currentUsage(0.0)
                                .entitlementUpdatedAt(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .feature(
                                    SubscriptionProvisionResponse.Data.Entitlement
                                        .UnionObjectVariant0
                                        .Feature
                                        .builder()
                                        .displayName("displayName")
                                        .featureStatus(
                                            SubscriptionProvisionResponse.Data.Entitlement
                                                .UnionObjectVariant0
                                                .Feature
                                                .FeatureStatus
                                                .NEW
                                        )
                                        .featureType(
                                            SubscriptionProvisionResponse.Data.Entitlement
                                                .UnionObjectVariant0
                                                .Feature
                                                .FeatureType
                                                .BOOLEAN
                                        )
                                        .refId("refId")
                                        .build()
                                )
                                .hasUnlimitedUsage(true)
                                .resetPeriod(
                                    SubscriptionProvisionResponse.Data.Entitlement
                                        .UnionObjectVariant0
                                        .ResetPeriod
                                        .YEAR
                                )
                                .usageLimit(0.0)
                                .usagePeriodAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .usagePeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .usagePeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .validUntil(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .status(SubscriptionProvisionResponse.Data.Status.SUCCESS)
                        .subscription(
                            SubscriptionProvisionResponse.Data.Subscription.builder()
                                .id("id")
                                .billingId("billingId")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customerId")
                                .paymentCollection(
                                    SubscriptionProvisionResponse.Data.Subscription
                                        .PaymentCollection
                                        .NOT_REQUIRED
                                )
                                .planId("planId")
                                .pricingType(
                                    SubscriptionProvisionResponse.Data.Subscription.PricingType.FREE
                                )
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .status(
                                    SubscriptionProvisionResponse.Data.Subscription.Status
                                        .PAYMENT_PENDING
                                )
                                .addAddon(
                                    SubscriptionProvisionResponse.Data.Subscription.Addon.builder()
                                        .id("id")
                                        .quantity(0L)
                                        .build()
                                )
                                .billingCycleAnchor(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .budget(
                                    SubscriptionProvisionResponse.Data.Subscription.Budget.builder()
                                        .hasSoftLimit(true)
                                        .limit(0.0)
                                        .build()
                                )
                                .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .cancelReason(
                                    SubscriptionProvisionResponse.Data.Subscription.CancelReason
                                        .UPGRADE_OR_DOWNGRADE
                                )
                                .addCoupon(
                                    SubscriptionProvisionResponse.Data.Subscription.Coupon.builder()
                                        .id("id")
                                        .name("name")
                                        .status(
                                            SubscriptionProvisionResponse.Data.Subscription.Coupon
                                                .Status
                                                .ACTIVE
                                        )
                                        .addAmountsOff(
                                            SubscriptionProvisionResponse.Data.Subscription.Coupon
                                                .AmountsOff
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SubscriptionProvisionResponse.Data.Subscription
                                                        .Coupon
                                                        .AmountsOff
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .percentOff(0.0)
                                        .build()
                                )
                                .currentBillingPeriodEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .currentBillingPeriodStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addFutureUpdate(
                                    SubscriptionProvisionResponse.Data.Subscription.FutureUpdate
                                        .builder()
                                        .scheduledExecutionTime(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .scheduleStatus(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .FutureUpdate
                                                .ScheduleStatus
                                                .PENDING_PAYMENT
                                        )
                                        .subscriptionScheduleType(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .FutureUpdate
                                                .SubscriptionScheduleType
                                                .DOWNGRADE
                                        )
                                        .targetPackage(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .FutureUpdate
                                                .TargetPackage
                                                .builder()
                                                .id("id")
                                                .build()
                                        )
                                        .build()
                                )
                                .latestInvoice(
                                    SubscriptionProvisionResponse.Data.Subscription.LatestInvoice
                                        .builder()
                                        .billingId("billingId")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .requiresAction(true)
                                        .status(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .LatestInvoice
                                                .Status
                                                .OPEN
                                        )
                                        .amountDue(0.0)
                                        .billingReason(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .LatestInvoice
                                                .BillingReason
                                                .BILLING_CYCLE
                                        )
                                        .currency("currency")
                                        .pdfUrl("pdfUrl")
                                        .total(0.0)
                                        .build()
                                )
                                .metadata(
                                    SubscriptionProvisionResponse.Data.Subscription.Metadata
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .minimumSpend(
                                    SubscriptionProvisionResponse.Data.Subscription.MinimumSpend
                                        .builder()
                                        .amount(0.0)
                                        .currency(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .MinimumSpend
                                                .Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .payingCustomerId("payingCustomerId")
                                .paymentCollectionMethod(
                                    SubscriptionProvisionResponse.Data.Subscription
                                        .PaymentCollectionMethod
                                        .CHARGE
                                )
                                .addPrice(
                                    SubscriptionProvisionResponse.Data.Subscription.Price.builder()
                                        .addonId("addonId")
                                        .amount(0.0)
                                        .baseCharge(true)
                                        .billingCountryCode("billingCountryCode")
                                        .blockSize(0.0)
                                        .currency(
                                            SubscriptionProvisionResponse.Data.Subscription.Price
                                                .Currency
                                                .USD
                                        )
                                        .featureId("featureId")
                                        .addTier(
                                            SubscriptionProvisionResponse.Data.Subscription.Price
                                                .Tier
                                                .builder()
                                                .flatPrice(
                                                    SubscriptionProvisionResponse.Data.Subscription
                                                        .Price
                                                        .Tier
                                                        .FlatPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            SubscriptionProvisionResponse.Data
                                                                .Subscription
                                                                .Price
                                                                .Tier
                                                                .FlatPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .unitPrice(
                                                    SubscriptionProvisionResponse.Data.Subscription
                                                        .Price
                                                        .Tier
                                                        .UnitPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            SubscriptionProvisionResponse.Data
                                                                .Subscription
                                                                .Price
                                                                .Tier
                                                                .UnitPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .upTo(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .resourceId("resourceId")
                                .addSubscriptionEntitlement(
                                    SubscriptionProvisionResponse.Data.Subscription
                                        .SubscriptionEntitlement
                                        .builder()
                                        .id("id")
                                        .type(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .SubscriptionEntitlement
                                                .Type
                                                .FEATURE
                                        )
                                        .build()
                                )
                                .trial(
                                    SubscriptionProvisionResponse.Data.Subscription.Trial.builder()
                                        .trialEndBehavior(
                                            SubscriptionProvisionResponse.Data.Subscription.Trial
                                                .TrialEndBehavior
                                                .CONVERT_TO_PAID
                                        )
                                        .build()
                                )
                                .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .checkoutBillingId("checkoutBillingId")
                        .checkoutUrl("checkoutUrl")
                        .isScheduled(true)
                        .build()
                )
                .build()

        assertThat(subscriptionProvisionResponse.data())
            .isEqualTo(
                SubscriptionProvisionResponse.Data.builder()
                    .id("id")
                    .addEntitlement(
                        SubscriptionProvisionResponse.Data.Entitlement.UnionObjectVariant0.builder()
                            .accessDeniedReason(
                                SubscriptionProvisionResponse.Data.Entitlement.UnionObjectVariant0
                                    .AccessDeniedReason
                                    .FEATURE_NOT_FOUND
                            )
                            .isGranted(true)
                            .type(
                                SubscriptionProvisionResponse.Data.Entitlement.UnionObjectVariant0
                                    .Type
                                    .FEATURE
                            )
                            .currentUsage(0.0)
                            .entitlementUpdatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .feature(
                                SubscriptionProvisionResponse.Data.Entitlement.UnionObjectVariant0
                                    .Feature
                                    .builder()
                                    .displayName("displayName")
                                    .featureStatus(
                                        SubscriptionProvisionResponse.Data.Entitlement
                                            .UnionObjectVariant0
                                            .Feature
                                            .FeatureStatus
                                            .NEW
                                    )
                                    .featureType(
                                        SubscriptionProvisionResponse.Data.Entitlement
                                            .UnionObjectVariant0
                                            .Feature
                                            .FeatureType
                                            .BOOLEAN
                                    )
                                    .refId("refId")
                                    .build()
                            )
                            .hasUnlimitedUsage(true)
                            .resetPeriod(
                                SubscriptionProvisionResponse.Data.Entitlement.UnionObjectVariant0
                                    .ResetPeriod
                                    .YEAR
                            )
                            .usageLimit(0.0)
                            .usagePeriodAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .usagePeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .usagePeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .validUntil(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .status(SubscriptionProvisionResponse.Data.Status.SUCCESS)
                    .subscription(
                        SubscriptionProvisionResponse.Data.Subscription.builder()
                            .id("id")
                            .billingId("billingId")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .customerId("customerId")
                            .paymentCollection(
                                SubscriptionProvisionResponse.Data.Subscription.PaymentCollection
                                    .NOT_REQUIRED
                            )
                            .planId("planId")
                            .pricingType(
                                SubscriptionProvisionResponse.Data.Subscription.PricingType.FREE
                            )
                            .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .status(
                                SubscriptionProvisionResponse.Data.Subscription.Status
                                    .PAYMENT_PENDING
                            )
                            .addAddon(
                                SubscriptionProvisionResponse.Data.Subscription.Addon.builder()
                                    .id("id")
                                    .quantity(0L)
                                    .build()
                            )
                            .billingCycleAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .budget(
                                SubscriptionProvisionResponse.Data.Subscription.Budget.builder()
                                    .hasSoftLimit(true)
                                    .limit(0.0)
                                    .build()
                            )
                            .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .cancelReason(
                                SubscriptionProvisionResponse.Data.Subscription.CancelReason
                                    .UPGRADE_OR_DOWNGRADE
                            )
                            .addCoupon(
                                SubscriptionProvisionResponse.Data.Subscription.Coupon.builder()
                                    .id("id")
                                    .name("name")
                                    .status(
                                        SubscriptionProvisionResponse.Data.Subscription.Coupon
                                            .Status
                                            .ACTIVE
                                    )
                                    .addAmountsOff(
                                        SubscriptionProvisionResponse.Data.Subscription.Coupon
                                            .AmountsOff
                                            .builder()
                                            .amount(0.0)
                                            .currency(
                                                SubscriptionProvisionResponse.Data.Subscription
                                                    .Coupon
                                                    .AmountsOff
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .percentOff(0.0)
                                    .build()
                            )
                            .currentBillingPeriodEnd(
                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                            )
                            .currentBillingPeriodStart(
                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                            )
                            .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .addFutureUpdate(
                                SubscriptionProvisionResponse.Data.Subscription.FutureUpdate
                                    .builder()
                                    .scheduledExecutionTime(
                                        OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                    )
                                    .scheduleStatus(
                                        SubscriptionProvisionResponse.Data.Subscription.FutureUpdate
                                            .ScheduleStatus
                                            .PENDING_PAYMENT
                                    )
                                    .subscriptionScheduleType(
                                        SubscriptionProvisionResponse.Data.Subscription.FutureUpdate
                                            .SubscriptionScheduleType
                                            .DOWNGRADE
                                    )
                                    .targetPackage(
                                        SubscriptionProvisionResponse.Data.Subscription.FutureUpdate
                                            .TargetPackage
                                            .builder()
                                            .id("id")
                                            .build()
                                    )
                                    .build()
                            )
                            .latestInvoice(
                                SubscriptionProvisionResponse.Data.Subscription.LatestInvoice
                                    .builder()
                                    .billingId("billingId")
                                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                    .requiresAction(true)
                                    .status(
                                        SubscriptionProvisionResponse.Data.Subscription
                                            .LatestInvoice
                                            .Status
                                            .OPEN
                                    )
                                    .amountDue(0.0)
                                    .billingReason(
                                        SubscriptionProvisionResponse.Data.Subscription
                                            .LatestInvoice
                                            .BillingReason
                                            .BILLING_CYCLE
                                    )
                                    .currency("currency")
                                    .pdfUrl("pdfUrl")
                                    .total(0.0)
                                    .build()
                            )
                            .metadata(
                                SubscriptionProvisionResponse.Data.Subscription.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .minimumSpend(
                                SubscriptionProvisionResponse.Data.Subscription.MinimumSpend
                                    .builder()
                                    .amount(0.0)
                                    .currency(
                                        SubscriptionProvisionResponse.Data.Subscription.MinimumSpend
                                            .Currency
                                            .USD
                                    )
                                    .build()
                            )
                            .payingCustomerId("payingCustomerId")
                            .paymentCollectionMethod(
                                SubscriptionProvisionResponse.Data.Subscription
                                    .PaymentCollectionMethod
                                    .CHARGE
                            )
                            .addPrice(
                                SubscriptionProvisionResponse.Data.Subscription.Price.builder()
                                    .addonId("addonId")
                                    .amount(0.0)
                                    .baseCharge(true)
                                    .billingCountryCode("billingCountryCode")
                                    .blockSize(0.0)
                                    .currency(
                                        SubscriptionProvisionResponse.Data.Subscription.Price
                                            .Currency
                                            .USD
                                    )
                                    .featureId("featureId")
                                    .addTier(
                                        SubscriptionProvisionResponse.Data.Subscription.Price.Tier
                                            .builder()
                                            .flatPrice(
                                                SubscriptionProvisionResponse.Data.Subscription
                                                    .Price
                                                    .Tier
                                                    .FlatPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        SubscriptionProvisionResponse.Data
                                                            .Subscription
                                                            .Price
                                                            .Tier
                                                            .FlatPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .unitPrice(
                                                SubscriptionProvisionResponse.Data.Subscription
                                                    .Price
                                                    .Tier
                                                    .UnitPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .currency(
                                                        SubscriptionProvisionResponse.Data
                                                            .Subscription
                                                            .Price
                                                            .Tier
                                                            .UnitPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .upTo(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .resourceId("resourceId")
                            .addSubscriptionEntitlement(
                                SubscriptionProvisionResponse.Data.Subscription
                                    .SubscriptionEntitlement
                                    .builder()
                                    .id("id")
                                    .type(
                                        SubscriptionProvisionResponse.Data.Subscription
                                            .SubscriptionEntitlement
                                            .Type
                                            .FEATURE
                                    )
                                    .build()
                            )
                            .trial(
                                SubscriptionProvisionResponse.Data.Subscription.Trial.builder()
                                    .trialEndBehavior(
                                        SubscriptionProvisionResponse.Data.Subscription.Trial
                                            .TrialEndBehavior
                                            .CONVERT_TO_PAID
                                    )
                                    .build()
                            )
                            .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .checkoutBillingId("checkoutBillingId")
                    .checkoutUrl("checkoutUrl")
                    .isScheduled(true)
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val subscriptionProvisionResponse =
            SubscriptionProvisionResponse.builder()
                .data(
                    SubscriptionProvisionResponse.Data.builder()
                        .id("id")
                        .addEntitlement(
                            SubscriptionProvisionResponse.Data.Entitlement.UnionObjectVariant0
                                .builder()
                                .accessDeniedReason(
                                    SubscriptionProvisionResponse.Data.Entitlement
                                        .UnionObjectVariant0
                                        .AccessDeniedReason
                                        .FEATURE_NOT_FOUND
                                )
                                .isGranted(true)
                                .type(
                                    SubscriptionProvisionResponse.Data.Entitlement
                                        .UnionObjectVariant0
                                        .Type
                                        .FEATURE
                                )
                                .currentUsage(0.0)
                                .entitlementUpdatedAt(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .feature(
                                    SubscriptionProvisionResponse.Data.Entitlement
                                        .UnionObjectVariant0
                                        .Feature
                                        .builder()
                                        .displayName("displayName")
                                        .featureStatus(
                                            SubscriptionProvisionResponse.Data.Entitlement
                                                .UnionObjectVariant0
                                                .Feature
                                                .FeatureStatus
                                                .NEW
                                        )
                                        .featureType(
                                            SubscriptionProvisionResponse.Data.Entitlement
                                                .UnionObjectVariant0
                                                .Feature
                                                .FeatureType
                                                .BOOLEAN
                                        )
                                        .refId("refId")
                                        .build()
                                )
                                .hasUnlimitedUsage(true)
                                .resetPeriod(
                                    SubscriptionProvisionResponse.Data.Entitlement
                                        .UnionObjectVariant0
                                        .ResetPeriod
                                        .YEAR
                                )
                                .usageLimit(0.0)
                                .usagePeriodAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .usagePeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .usagePeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .validUntil(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .status(SubscriptionProvisionResponse.Data.Status.SUCCESS)
                        .subscription(
                            SubscriptionProvisionResponse.Data.Subscription.builder()
                                .id("id")
                                .billingId("billingId")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customerId")
                                .paymentCollection(
                                    SubscriptionProvisionResponse.Data.Subscription
                                        .PaymentCollection
                                        .NOT_REQUIRED
                                )
                                .planId("planId")
                                .pricingType(
                                    SubscriptionProvisionResponse.Data.Subscription.PricingType.FREE
                                )
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .status(
                                    SubscriptionProvisionResponse.Data.Subscription.Status
                                        .PAYMENT_PENDING
                                )
                                .addAddon(
                                    SubscriptionProvisionResponse.Data.Subscription.Addon.builder()
                                        .id("id")
                                        .quantity(0L)
                                        .build()
                                )
                                .billingCycleAnchor(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .budget(
                                    SubscriptionProvisionResponse.Data.Subscription.Budget.builder()
                                        .hasSoftLimit(true)
                                        .limit(0.0)
                                        .build()
                                )
                                .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .cancelReason(
                                    SubscriptionProvisionResponse.Data.Subscription.CancelReason
                                        .UPGRADE_OR_DOWNGRADE
                                )
                                .addCoupon(
                                    SubscriptionProvisionResponse.Data.Subscription.Coupon.builder()
                                        .id("id")
                                        .name("name")
                                        .status(
                                            SubscriptionProvisionResponse.Data.Subscription.Coupon
                                                .Status
                                                .ACTIVE
                                        )
                                        .addAmountsOff(
                                            SubscriptionProvisionResponse.Data.Subscription.Coupon
                                                .AmountsOff
                                                .builder()
                                                .amount(0.0)
                                                .currency(
                                                    SubscriptionProvisionResponse.Data.Subscription
                                                        .Coupon
                                                        .AmountsOff
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .percentOff(0.0)
                                        .build()
                                )
                                .currentBillingPeriodEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .currentBillingPeriodStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .addFutureUpdate(
                                    SubscriptionProvisionResponse.Data.Subscription.FutureUpdate
                                        .builder()
                                        .scheduledExecutionTime(
                                            OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                        )
                                        .scheduleStatus(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .FutureUpdate
                                                .ScheduleStatus
                                                .PENDING_PAYMENT
                                        )
                                        .subscriptionScheduleType(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .FutureUpdate
                                                .SubscriptionScheduleType
                                                .DOWNGRADE
                                        )
                                        .targetPackage(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .FutureUpdate
                                                .TargetPackage
                                                .builder()
                                                .id("id")
                                                .build()
                                        )
                                        .build()
                                )
                                .latestInvoice(
                                    SubscriptionProvisionResponse.Data.Subscription.LatestInvoice
                                        .builder()
                                        .billingId("billingId")
                                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                        .requiresAction(true)
                                        .status(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .LatestInvoice
                                                .Status
                                                .OPEN
                                        )
                                        .amountDue(0.0)
                                        .billingReason(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .LatestInvoice
                                                .BillingReason
                                                .BILLING_CYCLE
                                        )
                                        .currency("currency")
                                        .pdfUrl("pdfUrl")
                                        .total(0.0)
                                        .build()
                                )
                                .metadata(
                                    SubscriptionProvisionResponse.Data.Subscription.Metadata
                                        .builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .minimumSpend(
                                    SubscriptionProvisionResponse.Data.Subscription.MinimumSpend
                                        .builder()
                                        .amount(0.0)
                                        .currency(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .MinimumSpend
                                                .Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .payingCustomerId("payingCustomerId")
                                .paymentCollectionMethod(
                                    SubscriptionProvisionResponse.Data.Subscription
                                        .PaymentCollectionMethod
                                        .CHARGE
                                )
                                .addPrice(
                                    SubscriptionProvisionResponse.Data.Subscription.Price.builder()
                                        .addonId("addonId")
                                        .amount(0.0)
                                        .baseCharge(true)
                                        .billingCountryCode("billingCountryCode")
                                        .blockSize(0.0)
                                        .currency(
                                            SubscriptionProvisionResponse.Data.Subscription.Price
                                                .Currency
                                                .USD
                                        )
                                        .featureId("featureId")
                                        .addTier(
                                            SubscriptionProvisionResponse.Data.Subscription.Price
                                                .Tier
                                                .builder()
                                                .flatPrice(
                                                    SubscriptionProvisionResponse.Data.Subscription
                                                        .Price
                                                        .Tier
                                                        .FlatPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            SubscriptionProvisionResponse.Data
                                                                .Subscription
                                                                .Price
                                                                .Tier
                                                                .FlatPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .unitPrice(
                                                    SubscriptionProvisionResponse.Data.Subscription
                                                        .Price
                                                        .Tier
                                                        .UnitPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .currency(
                                                            SubscriptionProvisionResponse.Data
                                                                .Subscription
                                                                .Price
                                                                .Tier
                                                                .UnitPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .upTo(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .resourceId("resourceId")
                                .addSubscriptionEntitlement(
                                    SubscriptionProvisionResponse.Data.Subscription
                                        .SubscriptionEntitlement
                                        .builder()
                                        .id("id")
                                        .type(
                                            SubscriptionProvisionResponse.Data.Subscription
                                                .SubscriptionEntitlement
                                                .Type
                                                .FEATURE
                                        )
                                        .build()
                                )
                                .trial(
                                    SubscriptionProvisionResponse.Data.Subscription.Trial.builder()
                                        .trialEndBehavior(
                                            SubscriptionProvisionResponse.Data.Subscription.Trial
                                                .TrialEndBehavior
                                                .CONVERT_TO_PAID
                                        )
                                        .build()
                                )
                                .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .checkoutBillingId("checkoutBillingId")
                        .checkoutUrl("checkoutUrl")
                        .isScheduled(true)
                        .build()
                )
                .build()

        val roundtrippedSubscriptionProvisionResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(subscriptionProvisionResponse),
                jacksonTypeRef<SubscriptionProvisionResponse>(),
            )

        assertThat(roundtrippedSubscriptionProvisionResponse)
            .isEqualTo(subscriptionProvisionResponse)
    }
}
