// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.subscriptions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.stigg.core.JsonValue
import io.stigg.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SubscriptionCreateResponseTest {

    @Test
    fun create() {
        val subscriptionCreateResponse =
            SubscriptionCreateResponse.builder()
                .data(
                    SubscriptionCreateResponse.Data.builder()
                        .id("id")
                        .addEntitlement(
                            SubscriptionCreateResponse.Data.Entitlement.builder()
                                .accessDeniedReason("accessDeniedReason")
                                .currentUsage(0.0)
                                .entitlementUpdatedAt(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .feature(
                                    SubscriptionCreateResponse.Data.Entitlement.Feature.builder()
                                        .refId("refId")
                                        .build()
                                )
                                .hasUnlimitedUsage(true)
                                .isGranted(true)
                                .resetPeriod(
                                    SubscriptionCreateResponse.Data.Entitlement.ResetPeriod.YEAR
                                )
                                .usageLimit(0.0)
                                .usagePeriodAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .usagePeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .usagePeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .status(SubscriptionCreateResponse.Data.Status.SUCCESS)
                        .checkoutBillingId("checkoutBillingId")
                        .checkoutUrl("checkoutUrl")
                        .isScheduled(true)
                        .subscription(
                            SubscriptionCreateResponse.Data.Subscription.builder()
                                .id("id")
                                .billingId("billingId")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customerId")
                                .paymentCollection(
                                    SubscriptionCreateResponse.Data.Subscription.PaymentCollection
                                        .NOT_REQUIRED
                                )
                                .planId("planId")
                                .pricingType(
                                    SubscriptionCreateResponse.Data.Subscription.PricingType.FREE
                                )
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .status(
                                    SubscriptionCreateResponse.Data.Subscription.Status
                                        .PAYMENT_PENDING
                                )
                                .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .cancelReason(
                                    SubscriptionCreateResponse.Data.Subscription.CancelReason
                                        .UPGRADE_OR_DOWNGRADE
                                )
                                .currentBillingPeriodEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .currentBillingPeriodStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .metadata(
                                    SubscriptionCreateResponse.Data.Subscription.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .payingCustomerId("payingCustomerId")
                                .paymentCollectionMethod(
                                    SubscriptionCreateResponse.Data.Subscription
                                        .PaymentCollectionMethod
                                        .CHARGE
                                )
                                .addPrice(
                                    SubscriptionCreateResponse.Data.Subscription.Price.builder()
                                        .addonId("addonId")
                                        .baseCharge(true)
                                        .blockSize(0.0)
                                        .featureId("featureId")
                                        .price(
                                            SubscriptionCreateResponse.Data.Subscription.Price
                                                .InnerPrice
                                                .builder()
                                                .amount(0.0)
                                                .billingCountryCode("billingCountryCode")
                                                .currency(
                                                    SubscriptionCreateResponse.Data.Subscription
                                                        .Price
                                                        .InnerPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .addTier(
                                            SubscriptionCreateResponse.Data.Subscription.Price.Tier
                                                .builder()
                                                .flatPrice(
                                                    SubscriptionCreateResponse.Data.Subscription
                                                        .Price
                                                        .Tier
                                                        .FlatPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .billingCountryCode("billingCountryCode")
                                                        .currency(
                                                            SubscriptionCreateResponse.Data
                                                                .Subscription
                                                                .Price
                                                                .Tier
                                                                .FlatPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .unitPrice(
                                                    SubscriptionCreateResponse.Data.Subscription
                                                        .Price
                                                        .Tier
                                                        .UnitPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .billingCountryCode("billingCountryCode")
                                                        .currency(
                                                            SubscriptionCreateResponse.Data
                                                                .Subscription
                                                                .Price
                                                                .Tier
                                                                .UnitPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .upTo(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .resourceId("resourceId")
                                .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .unitQuantity(1.0)
                                .build()
                        )
                        .build()
                )
                .build()

        assertThat(subscriptionCreateResponse.data())
            .isEqualTo(
                SubscriptionCreateResponse.Data.builder()
                    .id("id")
                    .addEntitlement(
                        SubscriptionCreateResponse.Data.Entitlement.builder()
                            .accessDeniedReason("accessDeniedReason")
                            .currentUsage(0.0)
                            .entitlementUpdatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .feature(
                                SubscriptionCreateResponse.Data.Entitlement.Feature.builder()
                                    .refId("refId")
                                    .build()
                            )
                            .hasUnlimitedUsage(true)
                            .isGranted(true)
                            .resetPeriod(
                                SubscriptionCreateResponse.Data.Entitlement.ResetPeriod.YEAR
                            )
                            .usageLimit(0.0)
                            .usagePeriodAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .usagePeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .usagePeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .status(SubscriptionCreateResponse.Data.Status.SUCCESS)
                    .checkoutBillingId("checkoutBillingId")
                    .checkoutUrl("checkoutUrl")
                    .isScheduled(true)
                    .subscription(
                        SubscriptionCreateResponse.Data.Subscription.builder()
                            .id("id")
                            .billingId("billingId")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .customerId("customerId")
                            .paymentCollection(
                                SubscriptionCreateResponse.Data.Subscription.PaymentCollection
                                    .NOT_REQUIRED
                            )
                            .planId("planId")
                            .pricingType(
                                SubscriptionCreateResponse.Data.Subscription.PricingType.FREE
                            )
                            .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .status(
                                SubscriptionCreateResponse.Data.Subscription.Status.PAYMENT_PENDING
                            )
                            .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .cancelReason(
                                SubscriptionCreateResponse.Data.Subscription.CancelReason
                                    .UPGRADE_OR_DOWNGRADE
                            )
                            .currentBillingPeriodEnd(
                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                            )
                            .currentBillingPeriodStart(
                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                            )
                            .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .metadata(
                                SubscriptionCreateResponse.Data.Subscription.Metadata.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .payingCustomerId("payingCustomerId")
                            .paymentCollectionMethod(
                                SubscriptionCreateResponse.Data.Subscription.PaymentCollectionMethod
                                    .CHARGE
                            )
                            .addPrice(
                                SubscriptionCreateResponse.Data.Subscription.Price.builder()
                                    .addonId("addonId")
                                    .baseCharge(true)
                                    .blockSize(0.0)
                                    .featureId("featureId")
                                    .price(
                                        SubscriptionCreateResponse.Data.Subscription.Price
                                            .InnerPrice
                                            .builder()
                                            .amount(0.0)
                                            .billingCountryCode("billingCountryCode")
                                            .currency(
                                                SubscriptionCreateResponse.Data.Subscription.Price
                                                    .InnerPrice
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .addTier(
                                        SubscriptionCreateResponse.Data.Subscription.Price.Tier
                                            .builder()
                                            .flatPrice(
                                                SubscriptionCreateResponse.Data.Subscription.Price
                                                    .Tier
                                                    .FlatPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .billingCountryCode("billingCountryCode")
                                                    .currency(
                                                        SubscriptionCreateResponse.Data.Subscription
                                                            .Price
                                                            .Tier
                                                            .FlatPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .unitPrice(
                                                SubscriptionCreateResponse.Data.Subscription.Price
                                                    .Tier
                                                    .UnitPrice
                                                    .builder()
                                                    .amount(0.0)
                                                    .billingCountryCode("billingCountryCode")
                                                    .currency(
                                                        SubscriptionCreateResponse.Data.Subscription
                                                            .Price
                                                            .Tier
                                                            .UnitPrice
                                                            .Currency
                                                            .USD
                                                    )
                                                    .build()
                                            )
                                            .upTo(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .resourceId("resourceId")
                            .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .unitQuantity(1.0)
                            .build()
                    )
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val subscriptionCreateResponse =
            SubscriptionCreateResponse.builder()
                .data(
                    SubscriptionCreateResponse.Data.builder()
                        .id("id")
                        .addEntitlement(
                            SubscriptionCreateResponse.Data.Entitlement.builder()
                                .accessDeniedReason("accessDeniedReason")
                                .currentUsage(0.0)
                                .entitlementUpdatedAt(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .feature(
                                    SubscriptionCreateResponse.Data.Entitlement.Feature.builder()
                                        .refId("refId")
                                        .build()
                                )
                                .hasUnlimitedUsage(true)
                                .isGranted(true)
                                .resetPeriod(
                                    SubscriptionCreateResponse.Data.Entitlement.ResetPeriod.YEAR
                                )
                                .usageLimit(0.0)
                                .usagePeriodAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .usagePeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .usagePeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .status(SubscriptionCreateResponse.Data.Status.SUCCESS)
                        .checkoutBillingId("checkoutBillingId")
                        .checkoutUrl("checkoutUrl")
                        .isScheduled(true)
                        .subscription(
                            SubscriptionCreateResponse.Data.Subscription.builder()
                                .id("id")
                                .billingId("billingId")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .customerId("customerId")
                                .paymentCollection(
                                    SubscriptionCreateResponse.Data.Subscription.PaymentCollection
                                        .NOT_REQUIRED
                                )
                                .planId("planId")
                                .pricingType(
                                    SubscriptionCreateResponse.Data.Subscription.PricingType.FREE
                                )
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .status(
                                    SubscriptionCreateResponse.Data.Subscription.Status
                                        .PAYMENT_PENDING
                                )
                                .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .cancelReason(
                                    SubscriptionCreateResponse.Data.Subscription.CancelReason
                                        .UPGRADE_OR_DOWNGRADE
                                )
                                .currentBillingPeriodEnd(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .currentBillingPeriodStart(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .metadata(
                                    SubscriptionCreateResponse.Data.Subscription.Metadata.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .payingCustomerId("payingCustomerId")
                                .paymentCollectionMethod(
                                    SubscriptionCreateResponse.Data.Subscription
                                        .PaymentCollectionMethod
                                        .CHARGE
                                )
                                .addPrice(
                                    SubscriptionCreateResponse.Data.Subscription.Price.builder()
                                        .addonId("addonId")
                                        .baseCharge(true)
                                        .blockSize(0.0)
                                        .featureId("featureId")
                                        .price(
                                            SubscriptionCreateResponse.Data.Subscription.Price
                                                .InnerPrice
                                                .builder()
                                                .amount(0.0)
                                                .billingCountryCode("billingCountryCode")
                                                .currency(
                                                    SubscriptionCreateResponse.Data.Subscription
                                                        .Price
                                                        .InnerPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .addTier(
                                            SubscriptionCreateResponse.Data.Subscription.Price.Tier
                                                .builder()
                                                .flatPrice(
                                                    SubscriptionCreateResponse.Data.Subscription
                                                        .Price
                                                        .Tier
                                                        .FlatPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .billingCountryCode("billingCountryCode")
                                                        .currency(
                                                            SubscriptionCreateResponse.Data
                                                                .Subscription
                                                                .Price
                                                                .Tier
                                                                .FlatPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .unitPrice(
                                                    SubscriptionCreateResponse.Data.Subscription
                                                        .Price
                                                        .Tier
                                                        .UnitPrice
                                                        .builder()
                                                        .amount(0.0)
                                                        .billingCountryCode("billingCountryCode")
                                                        .currency(
                                                            SubscriptionCreateResponse.Data
                                                                .Subscription
                                                                .Price
                                                                .Tier
                                                                .UnitPrice
                                                                .Currency
                                                                .USD
                                                        )
                                                        .build()
                                                )
                                                .upTo(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .resourceId("resourceId")
                                .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .unitQuantity(1.0)
                                .build()
                        )
                        .build()
                )
                .build()

        val roundtrippedSubscriptionCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(subscriptionCreateResponse),
                jacksonTypeRef<SubscriptionCreateResponse>(),
            )

        assertThat(roundtrippedSubscriptionCreateResponse).isEqualTo(subscriptionCreateResponse)
    }
}
