// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.subscriptions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.stigg.core.JsonValue
import io.stigg.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SubscriptionListPageResponseTest {

    @Test
    fun create() {
        val subscriptionListPageResponse =
            SubscriptionListPageResponse.builder()
                .addData(
                    SubscriptionListResponse.builder()
                        .id("id")
                        .billingId("billingId")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .customerId("customerId")
                        .paymentCollection(SubscriptionListResponse.PaymentCollection.NOT_REQUIRED)
                        .planId("planId")
                        .pricingType(SubscriptionListResponse.PricingType.FREE)
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .status(SubscriptionListResponse.Status.PAYMENT_PENDING)
                        .addAddon(
                            SubscriptionListResponse.Addon.builder().id("id").quantity(0L).build()
                        )
                        .billingCycleAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .budget(
                            SubscriptionListResponse.Budget.builder()
                                .hasSoftLimit(true)
                                .limit(0.0)
                                .build()
                        )
                        .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .cancelReason(SubscriptionListResponse.CancelReason.UPGRADE_OR_DOWNGRADE)
                        .addCoupon(
                            SubscriptionListResponse.Coupon.builder()
                                .id("id")
                                .name("name")
                                .status(SubscriptionListResponse.Coupon.Status.ACTIVE)
                                .addAmountsOff(
                                    SubscriptionListResponse.Coupon.AmountsOff.builder()
                                        .amount(0.0)
                                        .currency(
                                            SubscriptionListResponse.Coupon.AmountsOff.Currency.USD
                                        )
                                        .build()
                                )
                                .percentOff(0.0)
                                .build()
                        )
                        .currentBillingPeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currentBillingPeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addFutureUpdate(
                            SubscriptionListResponse.FutureUpdate.builder()
                                .scheduledExecutionTime(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .scheduleStatus(
                                    SubscriptionListResponse.FutureUpdate.ScheduleStatus
                                        .PENDING_PAYMENT
                                )
                                .subscriptionScheduleType(
                                    SubscriptionListResponse.FutureUpdate.SubscriptionScheduleType
                                        .DOWNGRADE
                                )
                                .targetPackage(
                                    SubscriptionListResponse.FutureUpdate.TargetPackage.builder()
                                        .id("id")
                                        .build()
                                )
                                .build()
                        )
                        .latestInvoice(
                            SubscriptionListResponse.LatestInvoice.builder()
                                .billingId("billingId")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .requiresAction(true)
                                .status(SubscriptionListResponse.LatestInvoice.Status.OPEN)
                                .amountDue(0.0)
                                .billingReason(
                                    SubscriptionListResponse.LatestInvoice.BillingReason
                                        .BILLING_CYCLE
                                )
                                .currency("currency")
                                .pdfUrl("pdfUrl")
                                .total(0.0)
                                .build()
                        )
                        .metadata(
                            SubscriptionListResponse.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .minimumSpend(
                            SubscriptionListResponse.MinimumSpend.builder()
                                .amount(0.0)
                                .currency(SubscriptionListResponse.MinimumSpend.Currency.USD)
                                .build()
                        )
                        .payingCustomerId("payingCustomerId")
                        .paymentCollectionMethod(
                            SubscriptionListResponse.PaymentCollectionMethod.CHARGE
                        )
                        .addPrice(
                            SubscriptionListResponse.Price.builder()
                                .addonId("addonId")
                                .amount(0.0)
                                .baseCharge(true)
                                .billingCountryCode("billingCountryCode")
                                .blockSize(0.0)
                                .currency(SubscriptionListResponse.Price.Currency.USD)
                                .featureId("featureId")
                                .addTier(
                                    SubscriptionListResponse.Price.Tier.builder()
                                        .flatPrice(
                                            SubscriptionListResponse.Price.Tier.FlatPrice.builder()
                                                .amount(0.0)
                                                .currency(
                                                    SubscriptionListResponse.Price.Tier.FlatPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .unitPrice(
                                            SubscriptionListResponse.Price.Tier.UnitPrice.builder()
                                                .amount(0.0)
                                                .currency(
                                                    SubscriptionListResponse.Price.Tier.UnitPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .upTo(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .resourceId("resourceId")
                        .addSubscriptionEntitlement(
                            SubscriptionListResponse.SubscriptionEntitlement.builder()
                                .id("id")
                                .type(SubscriptionListResponse.SubscriptionEntitlement.Type.FEATURE)
                                .build()
                        )
                        .trial(
                            SubscriptionListResponse.Trial.builder()
                                .trialEndBehavior(
                                    SubscriptionListResponse.Trial.TrialEndBehavior.CONVERT_TO_PAID
                                )
                                .build()
                        )
                        .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .pagination(
                    SubscriptionListPageResponse.Pagination.builder()
                        .next("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .prev("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        assertThat(subscriptionListPageResponse.data())
            .containsExactly(
                SubscriptionListResponse.builder()
                    .id("id")
                    .billingId("billingId")
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .customerId("customerId")
                    .paymentCollection(SubscriptionListResponse.PaymentCollection.NOT_REQUIRED)
                    .planId("planId")
                    .pricingType(SubscriptionListResponse.PricingType.FREE)
                    .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .status(SubscriptionListResponse.Status.PAYMENT_PENDING)
                    .addAddon(
                        SubscriptionListResponse.Addon.builder().id("id").quantity(0L).build()
                    )
                    .billingCycleAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .budget(
                        SubscriptionListResponse.Budget.builder()
                            .hasSoftLimit(true)
                            .limit(0.0)
                            .build()
                    )
                    .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .cancelReason(SubscriptionListResponse.CancelReason.UPGRADE_OR_DOWNGRADE)
                    .addCoupon(
                        SubscriptionListResponse.Coupon.builder()
                            .id("id")
                            .name("name")
                            .status(SubscriptionListResponse.Coupon.Status.ACTIVE)
                            .addAmountsOff(
                                SubscriptionListResponse.Coupon.AmountsOff.builder()
                                    .amount(0.0)
                                    .currency(
                                        SubscriptionListResponse.Coupon.AmountsOff.Currency.USD
                                    )
                                    .build()
                            )
                            .percentOff(0.0)
                            .build()
                    )
                    .currentBillingPeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .currentBillingPeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .addFutureUpdate(
                        SubscriptionListResponse.FutureUpdate.builder()
                            .scheduledExecutionTime(
                                OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                            )
                            .scheduleStatus(
                                SubscriptionListResponse.FutureUpdate.ScheduleStatus.PENDING_PAYMENT
                            )
                            .subscriptionScheduleType(
                                SubscriptionListResponse.FutureUpdate.SubscriptionScheduleType
                                    .DOWNGRADE
                            )
                            .targetPackage(
                                SubscriptionListResponse.FutureUpdate.TargetPackage.builder()
                                    .id("id")
                                    .build()
                            )
                            .build()
                    )
                    .latestInvoice(
                        SubscriptionListResponse.LatestInvoice.builder()
                            .billingId("billingId")
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .requiresAction(true)
                            .status(SubscriptionListResponse.LatestInvoice.Status.OPEN)
                            .amountDue(0.0)
                            .billingReason(
                                SubscriptionListResponse.LatestInvoice.BillingReason.BILLING_CYCLE
                            )
                            .currency("currency")
                            .pdfUrl("pdfUrl")
                            .total(0.0)
                            .build()
                    )
                    .metadata(
                        SubscriptionListResponse.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .minimumSpend(
                        SubscriptionListResponse.MinimumSpend.builder()
                            .amount(0.0)
                            .currency(SubscriptionListResponse.MinimumSpend.Currency.USD)
                            .build()
                    )
                    .payingCustomerId("payingCustomerId")
                    .paymentCollectionMethod(
                        SubscriptionListResponse.PaymentCollectionMethod.CHARGE
                    )
                    .addPrice(
                        SubscriptionListResponse.Price.builder()
                            .addonId("addonId")
                            .amount(0.0)
                            .baseCharge(true)
                            .billingCountryCode("billingCountryCode")
                            .blockSize(0.0)
                            .currency(SubscriptionListResponse.Price.Currency.USD)
                            .featureId("featureId")
                            .addTier(
                                SubscriptionListResponse.Price.Tier.builder()
                                    .flatPrice(
                                        SubscriptionListResponse.Price.Tier.FlatPrice.builder()
                                            .amount(0.0)
                                            .currency(
                                                SubscriptionListResponse.Price.Tier.FlatPrice
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .unitPrice(
                                        SubscriptionListResponse.Price.Tier.UnitPrice.builder()
                                            .amount(0.0)
                                            .currency(
                                                SubscriptionListResponse.Price.Tier.UnitPrice
                                                    .Currency
                                                    .USD
                                            )
                                            .build()
                                    )
                                    .upTo(0.0)
                                    .build()
                            )
                            .build()
                    )
                    .resourceId("resourceId")
                    .addSubscriptionEntitlement(
                        SubscriptionListResponse.SubscriptionEntitlement.builder()
                            .id("id")
                            .type(SubscriptionListResponse.SubscriptionEntitlement.Type.FEATURE)
                            .build()
                    )
                    .trial(
                        SubscriptionListResponse.Trial.builder()
                            .trialEndBehavior(
                                SubscriptionListResponse.Trial.TrialEndBehavior.CONVERT_TO_PAID
                            )
                            .build()
                    )
                    .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )
        assertThat(subscriptionListPageResponse.pagination())
            .isEqualTo(
                SubscriptionListPageResponse.Pagination.builder()
                    .next("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .prev("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val subscriptionListPageResponse =
            SubscriptionListPageResponse.builder()
                .addData(
                    SubscriptionListResponse.builder()
                        .id("id")
                        .billingId("billingId")
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .customerId("customerId")
                        .paymentCollection(SubscriptionListResponse.PaymentCollection.NOT_REQUIRED)
                        .planId("planId")
                        .pricingType(SubscriptionListResponse.PricingType.FREE)
                        .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .status(SubscriptionListResponse.Status.PAYMENT_PENDING)
                        .addAddon(
                            SubscriptionListResponse.Addon.builder().id("id").quantity(0L).build()
                        )
                        .billingCycleAnchor(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .budget(
                            SubscriptionListResponse.Budget.builder()
                                .hasSoftLimit(true)
                                .limit(0.0)
                                .build()
                        )
                        .cancellationDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .cancelReason(SubscriptionListResponse.CancelReason.UPGRADE_OR_DOWNGRADE)
                        .addCoupon(
                            SubscriptionListResponse.Coupon.builder()
                                .id("id")
                                .name("name")
                                .status(SubscriptionListResponse.Coupon.Status.ACTIVE)
                                .addAmountsOff(
                                    SubscriptionListResponse.Coupon.AmountsOff.builder()
                                        .amount(0.0)
                                        .currency(
                                            SubscriptionListResponse.Coupon.AmountsOff.Currency.USD
                                        )
                                        .build()
                                )
                                .percentOff(0.0)
                                .build()
                        )
                        .currentBillingPeriodEnd(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .currentBillingPeriodStart(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .effectiveEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .endDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .addFutureUpdate(
                            SubscriptionListResponse.FutureUpdate.builder()
                                .scheduledExecutionTime(
                                    OffsetDateTime.parse("2019-12-27T18:11:19.117Z")
                                )
                                .scheduleStatus(
                                    SubscriptionListResponse.FutureUpdate.ScheduleStatus
                                        .PENDING_PAYMENT
                                )
                                .subscriptionScheduleType(
                                    SubscriptionListResponse.FutureUpdate.SubscriptionScheduleType
                                        .DOWNGRADE
                                )
                                .targetPackage(
                                    SubscriptionListResponse.FutureUpdate.TargetPackage.builder()
                                        .id("id")
                                        .build()
                                )
                                .build()
                        )
                        .latestInvoice(
                            SubscriptionListResponse.LatestInvoice.builder()
                                .billingId("billingId")
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .requiresAction(true)
                                .status(SubscriptionListResponse.LatestInvoice.Status.OPEN)
                                .amountDue(0.0)
                                .billingReason(
                                    SubscriptionListResponse.LatestInvoice.BillingReason
                                        .BILLING_CYCLE
                                )
                                .currency("currency")
                                .pdfUrl("pdfUrl")
                                .total(0.0)
                                .build()
                        )
                        .metadata(
                            SubscriptionListResponse.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .minimumSpend(
                            SubscriptionListResponse.MinimumSpend.builder()
                                .amount(0.0)
                                .currency(SubscriptionListResponse.MinimumSpend.Currency.USD)
                                .build()
                        )
                        .payingCustomerId("payingCustomerId")
                        .paymentCollectionMethod(
                            SubscriptionListResponse.PaymentCollectionMethod.CHARGE
                        )
                        .addPrice(
                            SubscriptionListResponse.Price.builder()
                                .addonId("addonId")
                                .amount(0.0)
                                .baseCharge(true)
                                .billingCountryCode("billingCountryCode")
                                .blockSize(0.0)
                                .currency(SubscriptionListResponse.Price.Currency.USD)
                                .featureId("featureId")
                                .addTier(
                                    SubscriptionListResponse.Price.Tier.builder()
                                        .flatPrice(
                                            SubscriptionListResponse.Price.Tier.FlatPrice.builder()
                                                .amount(0.0)
                                                .currency(
                                                    SubscriptionListResponse.Price.Tier.FlatPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .unitPrice(
                                            SubscriptionListResponse.Price.Tier.UnitPrice.builder()
                                                .amount(0.0)
                                                .currency(
                                                    SubscriptionListResponse.Price.Tier.UnitPrice
                                                        .Currency
                                                        .USD
                                                )
                                                .build()
                                        )
                                        .upTo(0.0)
                                        .build()
                                )
                                .build()
                        )
                        .resourceId("resourceId")
                        .addSubscriptionEntitlement(
                            SubscriptionListResponse.SubscriptionEntitlement.builder()
                                .id("id")
                                .type(SubscriptionListResponse.SubscriptionEntitlement.Type.FEATURE)
                                .build()
                        )
                        .trial(
                            SubscriptionListResponse.Trial.builder()
                                .trialEndBehavior(
                                    SubscriptionListResponse.Trial.TrialEndBehavior.CONVERT_TO_PAID
                                )
                                .build()
                        )
                        .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .build()
                )
                .pagination(
                    SubscriptionListPageResponse.Pagination.builder()
                        .next("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .prev("182bd5e5-6e1a-4fe4-a799-aa6d9a6ab26e")
                        .build()
                )
                .build()

        val roundtrippedSubscriptionListPageResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(subscriptionListPageResponse),
                jacksonTypeRef<SubscriptionListPageResponse>(),
            )

        assertThat(roundtrippedSubscriptionListPageResponse).isEqualTo(subscriptionListPageResponse)
    }
}
