// File generated from our OpenAPI spec by Stainless.

package io.stigg.models.v1.subscriptions

import io.stigg.core.JsonValue
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SubscriptionUpdateParamsTest {

    @Test
    fun create() {
        SubscriptionUpdateParams.builder()
            .id("x")
            .addAddon(
                SubscriptionUpdateParams.Addon.builder().addonId("addonId").quantity(0.0).build()
            )
            .appliedCoupon(
                SubscriptionUpdateParams.AppliedCoupon.builder()
                    .billingCouponId("billingCouponId")
                    .configuration(
                        SubscriptionUpdateParams.AppliedCoupon.Configuration.builder()
                            .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .couponId("couponId")
                    .discount(
                        SubscriptionUpdateParams.AppliedCoupon.Discount.builder()
                            .addAmountsOff(
                                SubscriptionUpdateParams.AppliedCoupon.Discount.AmountsOff.builder()
                                    .amount(0.0)
                                    .currency(
                                        SubscriptionUpdateParams.AppliedCoupon.Discount.AmountsOff
                                            .Currency
                                            .USD
                                    )
                                    .build()
                            )
                            .description("description")
                            .durationInMonths(1.0)
                            .name("name")
                            .percentOff(1.0)
                            .build()
                    )
                    .promotionCode("promotionCode")
                    .build()
            )
            .awaitPaymentConfirmation(true)
            .billingInformation(
                SubscriptionUpdateParams.BillingInformation.builder()
                    .billingAddress(
                        SubscriptionUpdateParams.BillingInformation.BillingAddress.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postalCode")
                            .state("state")
                            .build()
                    )
                    .chargeOnBehalfOfAccount("chargeOnBehalfOfAccount")
                    .couponId("couponId")
                    .integrationId("integrationId")
                    .invoiceDaysUntilDue(0.0)
                    .isBackdated(true)
                    .isInvoicePaid(true)
                    .metadata(
                        SubscriptionUpdateParams.BillingInformation.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .prorationBehavior(
                        SubscriptionUpdateParams.BillingInformation.ProrationBehavior
                            .INVOICE_IMMEDIATELY
                    )
                    .addTaxId(
                        SubscriptionUpdateParams.BillingInformation.TaxId.builder()
                            .type("type")
                            .value("value")
                            .build()
                    )
                    .taxPercentage(0.0)
                    .addTaxRateId("string")
                    .build()
            )
            .billingPeriod(SubscriptionUpdateParams.BillingPeriod.MONTHLY)
            .budget(SubscriptionUpdateParams.Budget.builder().hasSoftLimit(true).limit(0.0).build())
            .addCharge(
                SubscriptionUpdateParams.Charge.builder()
                    .id("id")
                    .quantity(1.0)
                    .type(SubscriptionUpdateParams.Charge.Type.FEATURE)
                    .build()
            )
            .metadata(
                SubscriptionUpdateParams.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
            .minimumSpend(
                SubscriptionUpdateParams.MinimumSpend.builder()
                    .minimum(
                        SubscriptionUpdateParams.MinimumSpend.Minimum.builder()
                            .amount(0.0)
                            .currency(SubscriptionUpdateParams.MinimumSpend.Minimum.Currency.USD)
                            .build()
                    )
                    .build()
            )
            .addPriceOverride(
                SubscriptionUpdateParams.PriceOverride.builder()
                    .featureId("featureId")
                    .price(
                        SubscriptionUpdateParams.PriceOverride.Price.builder()
                            .amount(0.0)
                            .currency(SubscriptionUpdateParams.PriceOverride.Price.Currency.USD)
                            .build()
                    )
                    .build()
            )
            .promotionCode("promotionCode")
            .scheduleStrategy(SubscriptionUpdateParams.ScheduleStrategy.END_OF_BILLING_PERIOD)
            .addSubscriptionEntitlement(
                SubscriptionUpdateParams.SubscriptionEntitlement.builder()
                    .id("id")
                    .featureId("featureId")
                    .hasSoftLimit(true)
                    .hasUnlimitedUsage(true)
                    .monthlyResetPeriodConfiguration(
                        SubscriptionUpdateParams.SubscriptionEntitlement
                            .MonthlyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                SubscriptionUpdateParams.SubscriptionEntitlement
                                    .MonthlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .resetPeriod(SubscriptionUpdateParams.SubscriptionEntitlement.ResetPeriod.YEAR)
                    .usageLimit(0.0)
                    .weeklyResetPeriodConfiguration(
                        SubscriptionUpdateParams.SubscriptionEntitlement
                            .WeeklyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                SubscriptionUpdateParams.SubscriptionEntitlement
                                    .WeeklyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .yearlyResetPeriodConfiguration(
                        SubscriptionUpdateParams.SubscriptionEntitlement
                            .YearlyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                SubscriptionUpdateParams.SubscriptionEntitlement
                                    .YearlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .build()
            )
            .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
            .build()
    }

    @Test
    fun pathParams() {
        val params = SubscriptionUpdateParams.builder().id("x").build()

        assertThat(params._pathParam(0)).isEqualTo("x")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            SubscriptionUpdateParams.builder()
                .id("x")
                .addAddon(
                    SubscriptionUpdateParams.Addon.builder()
                        .addonId("addonId")
                        .quantity(0.0)
                        .build()
                )
                .appliedCoupon(
                    SubscriptionUpdateParams.AppliedCoupon.builder()
                        .billingCouponId("billingCouponId")
                        .configuration(
                            SubscriptionUpdateParams.AppliedCoupon.Configuration.builder()
                                .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .build()
                        )
                        .couponId("couponId")
                        .discount(
                            SubscriptionUpdateParams.AppliedCoupon.Discount.builder()
                                .addAmountsOff(
                                    SubscriptionUpdateParams.AppliedCoupon.Discount.AmountsOff
                                        .builder()
                                        .amount(0.0)
                                        .currency(
                                            SubscriptionUpdateParams.AppliedCoupon.Discount
                                                .AmountsOff
                                                .Currency
                                                .USD
                                        )
                                        .build()
                                )
                                .description("description")
                                .durationInMonths(1.0)
                                .name("name")
                                .percentOff(1.0)
                                .build()
                        )
                        .promotionCode("promotionCode")
                        .build()
                )
                .awaitPaymentConfirmation(true)
                .billingInformation(
                    SubscriptionUpdateParams.BillingInformation.builder()
                        .billingAddress(
                            SubscriptionUpdateParams.BillingInformation.BillingAddress.builder()
                                .city("city")
                                .country("country")
                                .line1("line1")
                                .line2("line2")
                                .postalCode("postalCode")
                                .state("state")
                                .build()
                        )
                        .chargeOnBehalfOfAccount("chargeOnBehalfOfAccount")
                        .couponId("couponId")
                        .integrationId("integrationId")
                        .invoiceDaysUntilDue(0.0)
                        .isBackdated(true)
                        .isInvoicePaid(true)
                        .metadata(
                            SubscriptionUpdateParams.BillingInformation.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .prorationBehavior(
                            SubscriptionUpdateParams.BillingInformation.ProrationBehavior
                                .INVOICE_IMMEDIATELY
                        )
                        .addTaxId(
                            SubscriptionUpdateParams.BillingInformation.TaxId.builder()
                                .type("type")
                                .value("value")
                                .build()
                        )
                        .taxPercentage(0.0)
                        .addTaxRateId("string")
                        .build()
                )
                .billingPeriod(SubscriptionUpdateParams.BillingPeriod.MONTHLY)
                .budget(
                    SubscriptionUpdateParams.Budget.builder().hasSoftLimit(true).limit(0.0).build()
                )
                .addCharge(
                    SubscriptionUpdateParams.Charge.builder()
                        .id("id")
                        .quantity(1.0)
                        .type(SubscriptionUpdateParams.Charge.Type.FEATURE)
                        .build()
                )
                .metadata(
                    SubscriptionUpdateParams.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("string"))
                        .build()
                )
                .minimumSpend(
                    SubscriptionUpdateParams.MinimumSpend.builder()
                        .minimum(
                            SubscriptionUpdateParams.MinimumSpend.Minimum.builder()
                                .amount(0.0)
                                .currency(
                                    SubscriptionUpdateParams.MinimumSpend.Minimum.Currency.USD
                                )
                                .build()
                        )
                        .build()
                )
                .addPriceOverride(
                    SubscriptionUpdateParams.PriceOverride.builder()
                        .featureId("featureId")
                        .price(
                            SubscriptionUpdateParams.PriceOverride.Price.builder()
                                .amount(0.0)
                                .currency(SubscriptionUpdateParams.PriceOverride.Price.Currency.USD)
                                .build()
                        )
                        .build()
                )
                .promotionCode("promotionCode")
                .scheduleStrategy(SubscriptionUpdateParams.ScheduleStrategy.END_OF_BILLING_PERIOD)
                .addSubscriptionEntitlement(
                    SubscriptionUpdateParams.SubscriptionEntitlement.builder()
                        .id("id")
                        .featureId("featureId")
                        .hasSoftLimit(true)
                        .hasUnlimitedUsage(true)
                        .monthlyResetPeriodConfiguration(
                            SubscriptionUpdateParams.SubscriptionEntitlement
                                .MonthlyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    SubscriptionUpdateParams.SubscriptionEntitlement
                                        .MonthlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .resetPeriod(
                            SubscriptionUpdateParams.SubscriptionEntitlement.ResetPeriod.YEAR
                        )
                        .usageLimit(0.0)
                        .weeklyResetPeriodConfiguration(
                            SubscriptionUpdateParams.SubscriptionEntitlement
                                .WeeklyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    SubscriptionUpdateParams.SubscriptionEntitlement
                                        .WeeklyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .yearlyResetPeriodConfiguration(
                            SubscriptionUpdateParams.SubscriptionEntitlement
                                .YearlyResetPeriodConfiguration
                                .builder()
                                .accordingTo(
                                    SubscriptionUpdateParams.SubscriptionEntitlement
                                        .YearlyResetPeriodConfiguration
                                        .AccordingTo
                                        .SUBSCRIPTION_START
                                )
                                .build()
                        )
                        .build()
                )
                .trialEndDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val body = params._body()

        assertThat(body.addons().getOrNull())
            .containsExactly(
                SubscriptionUpdateParams.Addon.builder().addonId("addonId").quantity(0.0).build()
            )
        assertThat(body.appliedCoupon())
            .contains(
                SubscriptionUpdateParams.AppliedCoupon.builder()
                    .billingCouponId("billingCouponId")
                    .configuration(
                        SubscriptionUpdateParams.AppliedCoupon.Configuration.builder()
                            .startDate(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .build()
                    )
                    .couponId("couponId")
                    .discount(
                        SubscriptionUpdateParams.AppliedCoupon.Discount.builder()
                            .addAmountsOff(
                                SubscriptionUpdateParams.AppliedCoupon.Discount.AmountsOff.builder()
                                    .amount(0.0)
                                    .currency(
                                        SubscriptionUpdateParams.AppliedCoupon.Discount.AmountsOff
                                            .Currency
                                            .USD
                                    )
                                    .build()
                            )
                            .description("description")
                            .durationInMonths(1.0)
                            .name("name")
                            .percentOff(1.0)
                            .build()
                    )
                    .promotionCode("promotionCode")
                    .build()
            )
        assertThat(body.awaitPaymentConfirmation()).contains(true)
        assertThat(body.billingInformation())
            .contains(
                SubscriptionUpdateParams.BillingInformation.builder()
                    .billingAddress(
                        SubscriptionUpdateParams.BillingInformation.BillingAddress.builder()
                            .city("city")
                            .country("country")
                            .line1("line1")
                            .line2("line2")
                            .postalCode("postalCode")
                            .state("state")
                            .build()
                    )
                    .chargeOnBehalfOfAccount("chargeOnBehalfOfAccount")
                    .couponId("couponId")
                    .integrationId("integrationId")
                    .invoiceDaysUntilDue(0.0)
                    .isBackdated(true)
                    .isInvoicePaid(true)
                    .metadata(
                        SubscriptionUpdateParams.BillingInformation.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .prorationBehavior(
                        SubscriptionUpdateParams.BillingInformation.ProrationBehavior
                            .INVOICE_IMMEDIATELY
                    )
                    .addTaxId(
                        SubscriptionUpdateParams.BillingInformation.TaxId.builder()
                            .type("type")
                            .value("value")
                            .build()
                    )
                    .taxPercentage(0.0)
                    .addTaxRateId("string")
                    .build()
            )
        assertThat(body.billingPeriod()).contains(SubscriptionUpdateParams.BillingPeriod.MONTHLY)
        assertThat(body.budget())
            .contains(
                SubscriptionUpdateParams.Budget.builder().hasSoftLimit(true).limit(0.0).build()
            )
        assertThat(body.charges().getOrNull())
            .containsExactly(
                SubscriptionUpdateParams.Charge.builder()
                    .id("id")
                    .quantity(1.0)
                    .type(SubscriptionUpdateParams.Charge.Type.FEATURE)
                    .build()
            )
        assertThat(body.metadata())
            .contains(
                SubscriptionUpdateParams.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("string"))
                    .build()
            )
        assertThat(body.minimumSpend())
            .contains(
                SubscriptionUpdateParams.MinimumSpend.builder()
                    .minimum(
                        SubscriptionUpdateParams.MinimumSpend.Minimum.builder()
                            .amount(0.0)
                            .currency(SubscriptionUpdateParams.MinimumSpend.Minimum.Currency.USD)
                            .build()
                    )
                    .build()
            )
        assertThat(body.priceOverrides().getOrNull())
            .containsExactly(
                SubscriptionUpdateParams.PriceOverride.builder()
                    .featureId("featureId")
                    .price(
                        SubscriptionUpdateParams.PriceOverride.Price.builder()
                            .amount(0.0)
                            .currency(SubscriptionUpdateParams.PriceOverride.Price.Currency.USD)
                            .build()
                    )
                    .build()
            )
        assertThat(body.promotionCode()).contains("promotionCode")
        assertThat(body.scheduleStrategy())
            .contains(SubscriptionUpdateParams.ScheduleStrategy.END_OF_BILLING_PERIOD)
        assertThat(body.subscriptionEntitlements().getOrNull())
            .containsExactly(
                SubscriptionUpdateParams.SubscriptionEntitlement.builder()
                    .id("id")
                    .featureId("featureId")
                    .hasSoftLimit(true)
                    .hasUnlimitedUsage(true)
                    .monthlyResetPeriodConfiguration(
                        SubscriptionUpdateParams.SubscriptionEntitlement
                            .MonthlyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                SubscriptionUpdateParams.SubscriptionEntitlement
                                    .MonthlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .resetPeriod(SubscriptionUpdateParams.SubscriptionEntitlement.ResetPeriod.YEAR)
                    .usageLimit(0.0)
                    .weeklyResetPeriodConfiguration(
                        SubscriptionUpdateParams.SubscriptionEntitlement
                            .WeeklyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                SubscriptionUpdateParams.SubscriptionEntitlement
                                    .WeeklyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .yearlyResetPeriodConfiguration(
                        SubscriptionUpdateParams.SubscriptionEntitlement
                            .YearlyResetPeriodConfiguration
                            .builder()
                            .accordingTo(
                                SubscriptionUpdateParams.SubscriptionEntitlement
                                    .YearlyResetPeriodConfiguration
                                    .AccordingTo
                                    .SUBSCRIPTION_START
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(body.trialEndDate()).contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params = SubscriptionUpdateParams.builder().id("x").build()

        val body = params._body()
    }
}
